export const apparelBrands = [
  "A4",
  "Allmade",
  "BELLA+CANVAS",
  "Brooks Brothers",
  "Bulwark",
  "Carhartt",
  "Champion",
  "Comfort Colors",
  "CornerStone",
  "Cotopaxi",
  "District",
  "Eddie Bauer",
  "Gildan",
  "Jerzees",
  "Mercer+Mettle",
  "New Era",
  "Next Level Apparel",
  "Nike",
  "OGIO",
  "Port & Co",
  "Port Authority",
  "Rabbit Skins",
  "Red Kap",
  "Richardson",
  "Russell Outdoors",
  "Sport-Tek",
  "Stanley/Stella",
  "The North Face",
  "TravisMathew",
  "Tommy Bahama",
  "Volunteer Knitwear",
  "Wink",
] as const;

export type ApparelBrand = (typeof apparelBrands)[number];
