import type { SampleProduct } from "./sample-products";

/**
 * Catalog expansion batch 4 — final fill from the nine source catalogs.
 * Covers:
 *  - Apparel SKU spec variants customers search by name (BC 3413, BC 6004,
 *    Next Level 6210, Champion S700, Hanes 5180, etc.)
 *  - Cap style variants (flat-bill, dad hat, rope hat, beanie variants)
 *  - Drinkware tier variants (24oz, 40oz with handle/straw lid options,
 *    Polar Camel decanter individual, glassware variants)
 *  - Wide-format / signage detail (yard sign sizes, large-format prints,
 *    car magnets, A-frame variants)
 *  - Trade-show + event (table runners, popup tents, retractable arches,
 *    badge holders, custom lanyards w/ printed clip)
 *  - Promo deep cuts (custom carabiners, beach balls, frisbees, golf tees,
 *    fidget toys, yo-yos, magnets)
 *  - Health/PPE remaining (face shields, digital thermometer, pulse ox,
 *    no-touch tools, sanitizer wipes)
 *  - Wedding/event (favor boxes, table number signs, koozies, ribbons,
 *    custom napkins)
 *  - Premium award additions (acrylic globes, perpetual towers, larger
 *    crystal pieces, sculpted glass)
 */
export const importedProductsBatch4: SampleProduct[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // APPAREL: brand-spec SKUs customers search by number
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "bella-canvas-6004-womens-tee",
    categorySlug: "apparel-headwear",
    subcategorySlug: "womens",
    title: "BELLA+CANVAS 6004 Women's Tee",
    shortDescription: "Slim-fit ring-spun women's crew — softer than 3001.",
    description: "Women's slim-fit ring-spun cotton tee. Softer hand than the unisex 3001. Pairs with screen print, DTF, embroidery.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["screen-print", "dtf", "embroidery"],
    brand: "BELLA+CANVAS",
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL"], Color: ["White", "Black", "Heather Grey", "Mauve", "Olive", "Rose Gold"] },
    heroPromptKey: "product:bc-6004-womens-tee",
  },
  {
    slug: "bella-canvas-3413-tri-blend",
    categorySlug: "apparel-headwear",
    subcategorySlug: "t-shirts",
    title: "BELLA+CANVAS 3413 Tri-Blend Tee",
    shortDescription: "Heathered tri-blend with vintage drape — bulk favorite.",
    description: "Tri-blend cotton/poly/rayon unisex tee with a heathered look and softer drape than the 3001.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["screen-print", "dtf", "embroidery"],
    brand: "BELLA+CANVAS",
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL", "3XL"], Color: ["Solid Black Tri", "Solid Navy Tri", "Heather Grey", "Heather Forest", "Heather Maroon"] },
    heroPromptKey: "product:bc-3413-tri-blend",
  },
  {
    slug: "next-level-6210-tee",
    categorySlug: "apparel-headwear",
    subcategorySlug: "t-shirts",
    title: "Next Level 6210 CVC Tee",
    shortDescription: "Cotton/poly CVC tee — ringspun softness, value pricing.",
    description: "Ringspun cotton/poly blend (CVC) tee with a soft hand and vibrant heathered colorways. Volume-friendly pricing.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["screen-print", "dtf"],
    brand: "Next Level Apparel",
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL"], Color: ["Black", "White", "Heather Grey", "Heather Navy", "Heather Cardinal"] },
    heroPromptKey: "product:nl-6210-tee",
  },
  {
    slug: "champion-s700-pullover-hoodie",
    categorySlug: "apparel-headwear",
    subcategorySlug: "sweatshirts-fleece",
    title: "Champion S700 Pullover Hoodie",
    shortDescription: "9oz Eco fleece hoodie — heritage softness.",
    description: "Champion's heritage 9oz Eco fleece hoodie. Mid-weight comfort with a refined cut and drawcord-free hood.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["screen-print", "embroidery", "dtf"],
    brand: "Champion",
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL"], Color: ["Black", "Navy", "Oxford Grey", "Maroon", "Charcoal Heather"] },
    heroPromptKey: "product:champion-s700-hoodie",
  },
  {
    slug: "hanes-5180-tagless-tee",
    categorySlug: "apparel-headwear",
    subcategorySlug: "t-shirts",
    title: "Hanes 5180 Beefy-T",
    shortDescription: "Heavyweight 6.1oz cotton tee — economy bulk.",
    description: "Heavyweight 6.1oz 100% cotton tee with tagless neck. Economy-friendly bulk option for fundraisers and giveaways.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 7,
    decorationMethods: ["screen-print", "dtf"],
    brand: "Hanes",
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL"], Color: ["White", "Black", "Navy", "Light Steel", "Deep Royal", "Cardinal"] },
    heroPromptKey: "product:hanes-5180-beefy-t",
  },
  {
    slug: "gildan-5000-cotton-tee",
    categorySlug: "apparel-headwear",
    subcategorySlug: "t-shirts",
    title: "Gildan 5000 Heavy Cotton Tee",
    shortDescription: "5.3oz heavy cotton — the all-time bulk-print classic.",
    description: "Gildan's heavy 100% cotton tee. The bulk-printing standard for two decades — broadest size run, deepest color choice, lowest unit cost.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 7,
    decorationMethods: ["screen-print", "dtf", "heat-transfer"],
    brand: "Gildan",
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"], Color: ["White", "Black", "Navy", "Royal", "Red", "Forest", "Sport Grey", "Maroon"] },
    heroPromptKey: "product:gildan-5000-tee",
    badges: ["Bulk Favorite"],
  },
  {
    slug: "gildan-2000-ultra-cotton",
    categorySlug: "apparel-headwear",
    subcategorySlug: "t-shirts",
    title: "Gildan 2000 Ultra Cotton Tee",
    shortDescription: "6oz ultra-cotton premium — heavier than 5000.",
    description: "Gildan's premium 6oz ultra-cotton tee. Heavier hand than the standard 5000, with a more polished drape.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 7,
    decorationMethods: ["screen-print", "dtf"],
    brand: "Gildan",
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL"], Color: ["White", "Black", "Navy", "Heather Grey", "Hunter", "Cardinal"] },
    heroPromptKey: "product:gildan-2000-tee",
  },
  {
    slug: "comfort-colors-1566-sweatshirt",
    categorySlug: "apparel-headwear",
    subcategorySlug: "sweatshirts-fleece",
    title: "Comfort Colors 1566 Crewneck",
    shortDescription: "Garment-dyed crewneck sweatshirt — vintage finish.",
    description: "Garment-dyed crewneck sweatshirt in Comfort Colors' signature pigment-dye palette. Heavier hand, soft drape.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["screen-print", "embroidery"],
    brand: "Comfort Colors",
    options: { Size: ["S", "M", "L", "XL", "2XL"], Color: ["Pepper", "Crimson", "Ivory", "Washed Denim", "Sandstone", "Chalky Mint"] },
    heroPromptKey: "product:cc-1566-crewneck",
  },
  {
    slug: "port-authority-l500-womens-polo",
    categorySlug: "apparel-headwear",
    subcategorySlug: "polos-knits",
    title: "Port Authority L500 Women's Polo",
    shortDescription: "Women's silk-touch polo — feminine cut, corporate-uniform pair.",
    description: "Wrinkle-resistant women's silk-touch polo with knit collar. Pairs with the men's K500 for matched corporate uniforms.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 8,
    decorationMethods: ["embroidery"],
    brand: "Port Authority",
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL", "3XL"], Color: ["Black", "Navy", "White", "Red", "Steel Grey"] },
    heroPromptKey: "product:pa-l500-womens-polo",
  },
  {
    slug: "sport-tek-st650-polo",
    categorySlug: "apparel-headwear",
    subcategorySlug: "polos-knits",
    title: "Sport-Tek ST650 Performance Polo",
    shortDescription: "Snag-proof performance polo — golf and corporate.",
    description: "Sport-Tek's snag-proof performance polo with moisture-wicking, anti-microbial finish. Athletic cut, holds embroidery cleanly.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 8,
    decorationMethods: ["embroidery"],
    brand: "Sport-Tek",
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"], Color: ["Black", "Navy", "True Royal", "Forest", "True Red"] },
    heroPromptKey: "product:st-st650-polo",
  },
  {
    slug: "ogio-soft-shell-jacket",
    categorySlug: "apparel-headwear",
    subcategorySlug: "outerwear",
    title: "OGIO Endurance Soft Shell Jacket",
    shortDescription: "Premium 3-layer soft shell — corporate-uniform staple.",
    description: "OGIO Endurance soft shell with bonded 3-layer construction, water- and wind-resistant. Premium corporate-uniform jacket.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 6,
    leadTimeDays: 11,
    decorationMethods: ["embroidery"],
    brand: "OGIO",
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"], Color: ["Black", "Navy", "Steel Grey"] },
    heroPromptKey: "product:ogio-soft-shell",
    badges: ["Premium"],
  },
  {
    slug: "the-north-face-tnf-puffer",
    categorySlug: "apparel-headwear",
    subcategorySlug: "outerwear",
    title: "The North Face Everyday Insulated Jacket",
    shortDescription: "TNF synthetic-insulated jacket — premium executive gift.",
    description: "Insulated everyday jacket from The North Face. Premium executive-gift item, embroidered chest with corporate logo.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 6,
    leadTimeDays: 14,
    decorationMethods: ["embroidery"],
    brand: "The North Face",
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL"], Color: ["Black", "Navy", "Asphalt Grey"] },
    heroPromptKey: "product:tnf-puffer-jacket",
    badges: ["Premium"],
  },
  {
    slug: "carhartt-sandstone-jacket",
    categorySlug: "apparel-headwear",
    subcategorySlug: "workwear",
    title: "Sandstone Workwear Jacket",
    shortDescription: "Heavy duck-canvas workwear jacket — trades and outdoor.",
    description: "Heavy duck-canvas workwear jacket with quilted lining, hammer loop, and reinforced cuffs. Trades and outdoor-crew staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 6,
    leadTimeDays: 11,
    decorationMethods: ["embroidery"],
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"], Color: ["Brown Duck", "Black", "Charcoal"] },
    heroPromptKey: "product:sandstone-workwear-jacket",
  },
  {
    slug: "carhartt-rugged-tee",
    categorySlug: "apparel-headwear",
    subcategorySlug: "workwear",
    title: "Rugged Long-Sleeve Workwear Tee",
    shortDescription: "Heavyweight long-sleeve work tee — built for jobsites.",
    description: "Heavyweight 7oz long-sleeve workwear tee. Reinforced shoulders, ribbed cuffs. Built for hard wear.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["screen-print", "embroidery"],
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"], Color: ["Black", "Heather Grey", "Navy", "Tan"] },
    heroPromptKey: "product:rugged-long-sleeve-tee",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CAPS / HEADWEAR — style variants
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "flat-bill-snapback",
    categorySlug: "apparel-headwear",
    subcategorySlug: "caps",
    title: "Flat-Bill Snapback Cap",
    shortDescription: "Modern flat-bill snapback — embroidered or patch.",
    description: "Modern flat-bill snapback with structured front and snap closure. Embroidered logo at front-center or leather patch.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["embroidery", "leather-patch"],
    options: { Color: ["Black", "Navy", "Charcoal", "Black/White", "Heather Grey/Black"] },
    heroPromptKey: "product:flat-bill-snapback",
  },
  {
    slug: "dad-hat",
    categorySlug: "apparel-headwear",
    subcategorySlug: "caps",
    title: "Unstructured Dad Hat",
    shortDescription: "Soft-front dad hat — vintage washed cotton.",
    description: "Unstructured 6-panel dad hat in washed cotton with curved bill and adjustable strap. Embroidered front-center.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["embroidery"],
    options: { Color: ["Khaki", "Navy", "Black", "Burgundy", "Hunter", "Stone"] },
    heroPromptKey: "product:dad-hat",
  },
  {
    slug: "rope-hat",
    categorySlug: "apparel-headwear",
    subcategorySlug: "caps",
    title: "Rope Snapback Cap",
    shortDescription: "Five-panel rope snapback — golf and outdoor brand staple.",
    description: "Five-panel snapback cap with rope detail across the brim. Embroidered or leather-patch front, popular with outdoor brands.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["embroidery", "leather-patch"],
    options: { Color: ["Charcoal/Black Rope", "Navy/White Rope", "Khaki/Black Rope", "Hunter/White Rope"] },
    heroPromptKey: "product:rope-hat",
  },
  {
    slug: "5-panel-camper-cap",
    categorySlug: "apparel-headwear",
    subcategorySlug: "caps",
    title: "5-Panel Camper Cap",
    shortDescription: "Vintage 5-panel camper cap — soft front, snap back.",
    description: "Five-panel camper-style cap with soft front and snap closure. Embroidered front patch or full-front print.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["embroidery"],
    options: { Color: ["Black", "Charcoal", "Navy", "Olive", "Khaki"] },
    heroPromptKey: "product:5-panel-camper-cap",
  },
  {
    slug: "cuffed-pom-beanie",
    categorySlug: "apparel-headwear",
    subcategorySlug: "beanies-visors",
    title: "Cuffed Beanie with Pom",
    shortDescription: "Knit cuffed beanie with faux-fur pom — winter favorite.",
    description: "Acrylic-knit cuffed beanie with detachable faux-fur pom. Embroidered front. Cool-weather giveaway favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["embroidery", "leather-patch"],
    options: { Color: ["Black", "Charcoal", "Navy", "Burgundy", "Pink"] },
    heroPromptKey: "product:cuffed-pom-beanie",
  },
  {
    slug: "trucker-hat-foam-front",
    categorySlug: "apparel-headwear",
    subcategorySlug: "caps",
    title: "Foam-Front Trucker Cap",
    shortDescription: "Old-school foam-front trucker — bold front imprint.",
    description: "Old-school foam-front trucker cap with mesh back and snap closure. Holds bold full-front screen prints.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["screen-print", "heat-transfer"],
    options: { Color: ["Black/Black", "Black/White", "Navy/White", "Red/White"] },
    heroPromptKey: "product:foam-front-trucker",
  },
  {
    slug: "bucket-hat",
    categorySlug: "apparel-headwear",
    subcategorySlug: "beanies-visors",
    title: "Bucket Hat",
    shortDescription: "Cotton bucket hat — festival, beach, outdoor brand.",
    description: "Soft-cotton bucket hat with side ventilation grommets. Embroidered front panel or all-over sublimation print.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["embroidery", "sublimation"],
    options: { Color: ["Khaki", "Black", "Navy", "Olive", "Stone"] },
    heroPromptKey: "product:bucket-hat",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // DRINKWARE — additional sizes/lid styles
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "polar-camel-24oz-tumbler",
    categorySlug: "drinkware",
    subcategorySlug: "tumblers",
    title: "Polar Camel 24oz Travel Tumbler",
    shortDescription: "24oz vacuum tumbler with handle — between 20oz and 40oz.",
    description: "24oz vacuum-insulated tumbler with carry handle and slide-lid. The mid-size between the standard 20oz and trending 40oz.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Stainless", "Sage", "Mauve", "Navy"] },
    heroPromptKey: "product:polar-camel-24oz",
  },
  {
    slug: "polar-camel-40oz-no-handle",
    categorySlug: "drinkware",
    subcategorySlug: "40oz-tumblers",
    title: "Polar Camel 40oz Slim Tumbler (No Handle)",
    shortDescription: "40oz slim profile — no handle, fits cup holders.",
    description: "Slim-profile 40oz vacuum tumbler without handle — fits in standard cup holders. Powder-coat finish, engraves clean silver.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Sage", "Stainless", "Mauve", "Charcoal"] },
    heroPromptKey: "product:polar-camel-40oz-slim",
  },
  {
    slug: "polar-camel-decanter-only",
    categorySlug: "drinkware",
    subcategorySlug: "wine-sets",
    title: "Crystal Whiskey Decanter",
    shortDescription: "Standalone crystal decanter — sand-etched front.",
    description: "Solid crystal whiskey decanter with stopper. Sand-etched front face for monogram or business mark. Premium gift solo.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["sand-etch"],
    heroPromptKey: "product:crystal-decanter-solo",
    badges: ["Premium"],
  },
  {
    slug: "wine-glass-set",
    categorySlug: "drinkware",
    subcategorySlug: "wine-sets",
    title: "Engraved Wine Glass Set (4-pack)",
    shortDescription: "Four 14oz crystal wine glasses — sand-etched.",
    description: "Set of four 14oz crystal wine glasses, sand-etched with monogram or short message. Wedding-favor and bridesmaid-gift staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 8,
    decorationMethods: ["sand-etch"],
    heroPromptKey: "product:wine-glass-set",
  },
  {
    slug: "champagne-flute-set",
    categorySlug: "drinkware",
    subcategorySlug: "wine-sets",
    title: "Engraved Champagne Flute Set (2-pack)",
    shortDescription: "Toasting flutes — wedding pair, sand-etched.",
    description: "Two crystal champagne toasting flutes, sand-etched with names and wedding date. Standard wedding-pair gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 8,
    decorationMethods: ["sand-etch"],
    heroPromptKey: "product:champagne-flute-set",
  },
  {
    slug: "beer-stein-engraved",
    categorySlug: "drinkware",
    subcategorySlug: "wine-sets",
    title: "Engraved Beer Stein",
    shortDescription: "16oz glass beer stein with handle — sand-etched.",
    description: "16oz glass beer stein with sturdy handle and dimpled body. Sand-etched front for monogram or pub-style logo.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["sand-etch"],
    heroPromptKey: "product:beer-stein-engraved",
  },
  {
    slug: "polar-camel-can-cooler-stainless",
    categorySlug: "drinkware",
    subcategorySlug: "tumblers",
    title: "Stainless Can Cooler (12oz)",
    shortDescription: "Vacuum-insulated 12oz can holder — keeps cans cold.",
    description: "Stainless vacuum-insulated 12oz can holder. Slip-on snug fit, threaded lid, engraves clean. Tailgate and patio favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Stainless", "Navy", "Red"] },
    heroPromptKey: "product:stainless-can-cooler",
  },
  {
    slug: "kids-tumbler-with-straw",
    categorySlug: "drinkware",
    subcategorySlug: "tumblers",
    title: "Kids' Tumbler with Straw",
    shortDescription: "16oz kids' tumbler with leak-resistant straw lid.",
    description: "Insulated 16oz kids' tumbler with leak-resistant straw lid. Bright colors, engraves cleanly. School and party favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving", "uv-print"],
    options: { Color: ["Pink", "Teal", "Yellow", "Purple", "Royal"] },
    heroPromptKey: "product:kids-tumbler-straw",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // SIGNAGE / WIDE FORMAT — additional formats
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "yard-sign-12x18",
    categorySlug: "custom-printing",
    subcategorySlug: "yard-signs",
    title: "12×18 Yard Sign",
    shortDescription: "Compact yard sign — small political, real estate.",
    description: "Compact 12×18 corrugated plastic yard sign with H-stake. Smaller than the standard 24×18 — political and small-business favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 4,
    decorationMethods: ["digital-print"],
    heroPromptKey: "product:yard-sign-12x18",
  },
  {
    slug: "yard-sign-large-36x24",
    categorySlug: "custom-printing",
    subcategorySlug: "yard-signs",
    title: "Large 36×24 Yard Sign",
    shortDescription: "Large yard sign — high-visibility business display.",
    description: "Large 36×24 corrugated plastic yard sign for high-visibility outdoor displays. Includes heavy-duty H-stake.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 5,
    leadTimeDays: 4,
    decorationMethods: ["digital-print"],
    options: { Sides: ["Single", "Double"] },
    heroPromptKey: "product:yard-sign-36x24",
  },
  {
    slug: "coroplast-real-estate-frame",
    categorySlug: "custom-printing",
    subcategorySlug: "yard-signs",
    title: "Real-Estate Frame & Sign Kit",
    shortDescription: "Metal frame + 24×18 sign + rider — agent kit.",
    description: "Heavy-duty metal frame with screw mounts, 24×18 corrugated sign, and rider strip. Real-estate agent essential.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 5,
    leadTimeDays: 7,
    decorationMethods: ["digital-print"],
    heroPromptKey: "product:re-frame-kit",
  },
  {
    slug: "magnetic-business-sign",
    categorySlug: "custom-printing",
    subcategorySlug: "car-door-magnets",
    title: "Magnetic Business Sign",
    shortDescription: "Heavy magnetic sign — vehicle, fridge, file cabinet.",
    description: "Heavy 30mil magnetic sign in custom dimensions. Sticks to any ferrous surface — vehicle door, fridge, file cabinet.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["digital-print"],
    options: { Size: ["12×18", "18×24", "24×24", "Custom"] },
    heroPromptKey: "product:magnetic-business-sign",
  },
  {
    slug: "vehicle-wrap-partial",
    categorySlug: "custom-printing",
    subcategorySlug: "vinyl-lettering",
    title: "Vehicle Vinyl Decal Set",
    shortDescription: "Custom vehicle vinyl set — door logos, rear graphics.",
    description: "Custom-cut vehicle vinyl decals for door logos, rear-glass branding, and side-panel call-outs. Premium 6-year outdoor vinyl.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["digital-print"],
    heroPromptKey: "product:vehicle-vinyl-set",
  },
  {
    slug: "hanging-sign-banner-pole",
    categorySlug: "custom-printing",
    subcategorySlug: "banners",
    title: "Pole-Pocket Hanging Banner",
    shortDescription: "Banner with sewn pole pockets — easy hang on bars.",
    description: "Vinyl or fabric banner with sewn pole pockets at top and bottom. Slides over standard banner poles for clean hanging.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 6,
    decorationMethods: ["digital-print"],
    options: { Size: ["3×6", "4×8", "Custom"], Material: ["Vinyl", "Fabric"] },
    heroPromptKey: "product:pole-pocket-banner",
  },
  {
    slug: "yard-letter-set",
    categorySlug: "custom-printing",
    subcategorySlug: "graduation-yard-signs",
    title: "Yard Letter Set (24-inch)",
    shortDescription: "Coroplast yard letters — birthdays, graduations, events.",
    description: "Set of 24-inch coroplast yard letters that spell out 'CONGRATS' or any custom message. Includes ground stakes.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 6,
    decorationMethods: ["digital-print"],
    heroPromptKey: "product:yard-letter-set",
  },
  {
    slug: "exhibit-pop-up-tent",
    categorySlug: "custom-printing",
    subcategorySlug: "exhibit-booths",
    title: "10×10 Pop-Up Event Tent",
    shortDescription: "Custom 10×10 event canopy with sublimated graphics.",
    description: "Standard 10×10 outdoor event canopy with custom-printed roof and side-panel graphics. Trade-show, race-day, festival.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 18,
    decorationMethods: ["sublimation"],
    options: { Size: ["10×10", "10×20"] },
    heroPromptKey: "product:popup-event-tent",
    badges: ["Premium"],
  },
  {
    slug: "table-runner-printed",
    categorySlug: "custom-printing",
    subcategorySlug: "table-covers",
    title: "Printed Table Runner",
    shortDescription: "30×72 sublimated table runner — accent for trade-show tables.",
    description: "Polyester table runner, 30×72, with full-color sublimated graphic. Drapes over standard cover for layered branding.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 8,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:table-runner-printed",
  },
  {
    slug: "popup-display-board",
    categorySlug: "custom-printing",
    subcategorySlug: "exhibit-booths",
    title: "Pop-Up Display Board",
    shortDescription: "Curved fabric pop-up backdrop — single panel.",
    description: "Curved fabric pop-up display board with carrying case. Single-panel velcro graphic for trade-show booths.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 14,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:popup-display-board",
  },
  {
    slug: "media-wall-large",
    categorySlug: "custom-printing",
    subcategorySlug: "trade-show-backdrops",
    title: "20ft Tension Media Wall",
    shortDescription: "Large 20ft tension media wall — major trade show.",
    description: "Large 20ft tension-fabric media wall on aluminum frame. Major trade-show booth backdrop. Wheeled hard case included.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 21,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:media-wall-20ft",
    badges: ["Premium"],
  },
  {
    slug: "large-format-poster-24x36",
    categorySlug: "custom-printing",
    subcategorySlug: "posters-large-prints",
    title: "Large-Format Poster 24×36",
    shortDescription: "Standard 24×36 indoor poster — events, conferences.",
    description: "Standard 24×36 full-color poster on satin or matte stock. Conference signage, event displays, indoor announcements.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: ["digital-print"],
    options: { Stock: ["Satin", "Matte", "Photo Gloss"] },
    heroPromptKey: "product:large-poster-24x36",
  },
  {
    slug: "large-format-poster-36x48",
    categorySlug: "custom-printing",
    subcategorySlug: "posters-large-prints",
    title: "Extra-Large Poster 36×48",
    shortDescription: "Extra-large 36×48 indoor poster — lobby, retail.",
    description: "Extra-large 36×48 full-color poster for lobby and retail displays. Choose satin, matte, or photo gloss.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["digital-print"],
    heroPromptKey: "product:large-poster-36x48",
  },
  {
    slug: "blueprint-printing",
    categorySlug: "custom-printing",
    subcategorySlug: "posters-large-prints",
    title: "Architectural Blueprint Print",
    shortDescription: "Wide-format engineering / architecture prints.",
    description: "Wide-format engineering and architecture prints. Standard sizes 18×24, 24×36, 30×42. Bond, vellum, or mylar.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 3,
    decorationMethods: ["digital-print"],
    options: { Size: ["18×24", "24×36", "30×42"], Stock: ["Bond", "Vellum", "Mylar"] },
    heroPromptKey: "product:blueprint-printing",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PROMO / EVENT / SWAG
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "carabiner-keychain",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Aluminum Carabiner Keychain",
    shortDescription: "Aluminum carabiner with split ring — engraved.",
    description: "Aluminum carabiner clip with split ring. Laser engraves a clean mark. Outdoor brand and event-swag favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Silver", "Red", "Blue", "Green"] },
    heroPromptKey: "product:carabiner-keychain",
  },
  {
    slug: "beach-ball-printed",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Imprinted Beach Ball",
    shortDescription: "Inflatable beach ball — pool parties and resort events.",
    description: "12-inch or 16-inch inflatable beach ball with custom-printed panels. Pool parties, resort events, summer giveaways.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 11,
    decorationMethods: ["uv-print"],
    options: { Size: ["12\"", "16\""] },
    heroPromptKey: "product:beach-ball-printed",
  },
  {
    slug: "frisbee-flying-disc",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Imprinted Flying Disc",
    shortDescription: "Standard 9-inch flying disc — outdoor giveaway.",
    description: "Standard 9-inch flying disc with single-color logo imprint. Outdoor festival, summer-camp, race-day giveaway.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 9,
    decorationMethods: ["uv-print"],
    options: { Color: ["White", "Red", "Blue", "Yellow", "Green", "Pink"] },
    heroPromptKey: "product:frisbee-flying-disc",
  },
  {
    slug: "golf-tee-pack",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Imprinted Golf Tee Pack",
    shortDescription: "Pack of 25 wooden golf tees — branded sleeve.",
    description: "Pack of 25 standard wooden golf tees in a branded paper sleeve. Tournament and golf-event giveaway.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 7,
    decorationMethods: ["digital-print"],
    heroPromptKey: "product:golf-tee-pack",
  },
  {
    slug: "golf-ball-marker",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Custom Golf Ball Marker",
    shortDescription: "Magnetic golf ball marker — engraved coin design.",
    description: "Magnetic golf ball marker with engraved coin design that snaps to a hat clip or money clip. Tournament favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving", "uv-print"],
    heroPromptKey: "product:golf-ball-marker",
  },
  {
    slug: "imprinted-yo-yo",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Imprinted Yo-Yo",
    shortDescription: "Classic plastic yo-yo — full-color UV imprint.",
    description: "Standard plastic yo-yo with full-color UV imprint on both sides. Trade-show staple for kid-friendly booths.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 9,
    decorationMethods: ["uv-print"],
    options: { Color: ["Red", "Blue", "Black", "Green", "Yellow"] },
    heroPromptKey: "product:imprinted-yo-yo",
  },
  {
    slug: "fidget-spinner-printed",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Custom Fidget Spinner",
    shortDescription: "Branded fidget spinner — kids and back-to-school promo.",
    description: "Standard tri-arm fidget spinner with full-color UV-printed center cap. Back-to-school and kids'-event promotional.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 11,
    decorationMethods: ["uv-print"],
    heroPromptKey: "product:fidget-spinner-printed",
  },
  {
    slug: "promotional-magnet-2x3",
    categorySlug: "custom-printing",
    subcategorySlug: "magnet-calendars",
    title: "Custom Refrigerator Magnet (2×3)",
    shortDescription: "Standard 2×3 fridge magnet — full color.",
    description: "Custom 2×3 die-cut refrigerator magnet, full color, on heavy magnet stock. Bulk-friendly for marketing campaigns.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 6,
    decorationMethods: ["digital-print"],
    heroPromptKey: "product:promotional-magnet",
  },
  {
    slug: "wedding-favor-box",
    categorySlug: "custom-printing",
    subcategorySlug: "holiday-cards",
    title: "Wedding Favor Box",
    shortDescription: "Folded paperboard favor box with custom print.",
    description: "Pre-scored paperboard wedding favor box with custom-printed exterior. Holds candies, mints, or small trinkets.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 9,
    decorationMethods: ["digital-print"],
    options: { Size: ["2×2×2", "3×3×3"] },
    heroPromptKey: "product:wedding-favor-box",
  },
  {
    slug: "table-number-signs",
    categorySlug: "custom-printing",
    subcategorySlug: "table-tents",
    title: "Wedding Table Number Signs",
    shortDescription: "Set of folded table-number tents — wedding reception.",
    description: "Set of 10 or 20 folded table-number tents on heavy stock. Wedding-reception staple. Custom design or simple numbering.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["digital-print"],
    options: { Set: ["Set of 10", "Set of 20"] },
    heroPromptKey: "product:table-number-signs",
  },
  {
    slug: "custom-printed-napkin",
    categorySlug: "custom-printing",
    subcategorySlug: "holiday-cards",
    title: "Custom Printed Cocktail Napkin",
    shortDescription: "5×5 cocktail napkin with foil-stamped monogram.",
    description: "Three-ply 5×5 cocktail napkins with foil-stamped or printed custom monogram. Wedding and bar-event favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 9,
    decorationMethods: ["foil"],
    heroPromptKey: "product:cocktail-napkin",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // HEALTH / PPE EXPANSION
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "face-shield",
    categorySlug: "apparel-headwear",
    subcategorySlug: "personal-protection",
    title: "Reusable Face Shield",
    shortDescription: "Adjustable face shield with foam brow.",
    description: "Anti-fog reusable face shield with adjustable strap and foam brow. Imprinted logo on the strap or shield band.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["uv-print"],
    heroPromptKey: "product:face-shield",
  },
  {
    slug: "thermometer-digital",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Digital No-Touch Thermometer",
    shortDescription: "Infrared no-touch thermometer — clinic / school giveaway.",
    description: "Infrared no-touch thermometer with display. Custom-imprinted face plate. Health-fair and clinic giveaway.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 14,
    decorationMethods: ["uv-print"],
    heroPromptKey: "product:thermometer-digital",
  },
  {
    slug: "sanitizer-wipes-pack",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Sanitizer Wipes Pack",
    shortDescription: "10-count sanitizer wipes — branded pouch.",
    description: "10-count individually wrapped sanitizer wipes in a branded pouch. Office and event giveaway.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 9,
    decorationMethods: ["digital-print"],
    heroPromptKey: "product:sanitizer-wipes",
  },
  {
    slug: "no-touch-tool",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "No-Touch Door & Button Tool",
    shortDescription: "Brass no-touch keychain tool — pulls doors, presses buttons.",
    description: "Solid brass no-touch keychain tool — opens doors, presses elevator buttons. Engrave the body for promo or clinic giveaway.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:no-touch-tool",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // TECH / OFFICE EXPANSION
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "stylus-pen-2in1",
    categorySlug: "custom-printing",
    subcategorySlug: "address-labels",
    title: "Stylus Pen 2-in-1",
    shortDescription: "Pen with capacitive stylus tip — works on phones/tablets.",
    description: "Click pen with rubberized capacitive stylus tip on the cap. Works on touch screens. Tech-event and conference giveaway.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 8,
    decorationMethods: ["uv-print"],
    options: { Color: ["Black", "Silver", "Red", "Blue"] },
    heroPromptKey: "product:stylus-pen-2in1",
  },
  {
    slug: "charging-cable-3in1",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "3-in-1 Charging Cable",
    shortDescription: "USB-A to USB-C/Lightning/Micro-USB — leatherette pouch.",
    description: "Versatile 3-in-1 charging cable in a leatherette pouch. Engrave the pouch. Conference and corporate-gift staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 11,
    decorationMethods: ["laser-engraving"],
    options: { Pouch: ["Black/Silver", "Rustic/Gold"] },
    heroPromptKey: "product:charging-cable-3in1",
  },
  {
    slug: "wireless-charging-pad",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Wireless Charging Pad",
    shortDescription: "Slim wireless charging pad — engraved leatherette top.",
    description: "Slim 10W wireless Qi charging pad with engraved leatherette top panel. Premium executive desk gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 12,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Wine/Gold"] },
    heroPromptKey: "product:wireless-charging-pad",
  },
  {
    slug: "earbuds-corded-promo",
    categorySlug: "photo-gifts",
    subcategorySlug: "phone-accessories",
    title: "Promotional Corded Earbuds",
    shortDescription: "Standard corded earbuds — bulk-friendly tech swag.",
    description: "Standard corded 3.5mm earbuds in a custom-printed paper case. Trade-show, school, conference giveaway.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 11,
    decorationMethods: ["uv-print"],
    options: { Color: ["White", "Black"] },
    heroPromptKey: "product:earbuds-corded-promo",
  },
  {
    slug: "tablet-stand-engraved",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Engraved Wooden Tablet Stand",
    shortDescription: "Walnut tablet stand — engraved logo.",
    description: "Solid walnut tablet stand with engraved face. Holds standard 7\"–13\" tablets. Premium executive desk gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:tablet-stand-engraved",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PHOTO GIFTS — additional
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "photo-magnet-3x3",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Custom Photo Magnet (3×3)",
    shortDescription: "3×3 fridge magnet with sublimated photo.",
    description: "Standard 3×3 die-cut refrigerator magnet with sublimated full-color photo or graphic.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 6,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:photo-magnet-3x3",
  },
  {
    slug: "photo-puzzle-30",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Mini Photo Puzzle (30 piece)",
    shortDescription: "30-piece photo puzzle — kids' birthday party favor.",
    description: "30-piece photo jigsaw puzzle in a small gift box. Easier for younger kids; party-favor friendly.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:photo-puzzle-30",
  },
  {
    slug: "photo-clock-wall",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Photo Wall Clock",
    shortDescription: "10-inch wall clock with sublimated photo face.",
    description: "10-inch silent quartz wall clock with full-color photo on the face. Custom photo or company logo.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:photo-clock-wall",
  },
  {
    slug: "photo-coaster-set-4pack",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Photo Coaster Set",
    shortDescription: "4-pack of sublimated photo coasters.",
    description: "Four square coasters with full-color sublimated photos and cork backing. Personalized housewarming gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 6,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:photo-coaster-set",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CORPORATE AWARDS — additional sizes / shapes
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "crystal-pyramid-award",
    categorySlug: "corporate-awards",
    subcategorySlug: "crystal-awards",
    title: "Crystal Pyramid Award",
    shortDescription: "Optical crystal pyramid — clean modern recognition.",
    description: "Solid optical crystal pyramid award with sand-etched front face. Clean, modern recognition piece.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["sand-etch"],
    options: { Size: ["6\"", "8\"", "10\""] },
    heroPromptKey: "product:crystal-pyramid",
  },
  {
    slug: "crystal-bookend-pair",
    categorySlug: "corporate-awards",
    subcategorySlug: "desk-pieces",
    title: "Crystal Bookend Pair",
    shortDescription: "Optical crystal bookend pair — engraved presentation.",
    description: "Pair of solid optical crystal bookends with engraved presentation text. Premium executive desk piece.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 12,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:crystal-bookend-pair",
    badges: ["Premium"],
  },
  {
    slug: "perpetual-tower",
    categorySlug: "corporate-awards",
    subcategorySlug: "perpetual-plaques",
    title: "Perpetual Tower Award",
    shortDescription: "Tower-format perpetual award — tabletop annual recognition.",
    description: "Tabletop tower-format perpetual award with rotating annual plates. For yearly champion or top-performer programs.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 14,
    decorationMethods: ["laser-engraving"],
    options: { Plates: ["10 plates", "20 plates"] },
    heroPromptKey: "product:perpetual-tower",
  },
  {
    slug: "executive-desk-set",
    categorySlug: "corporate-awards",
    subcategorySlug: "desk-pieces",
    title: "Executive Desk Set",
    shortDescription: "Pen + clock + business-card holder on a marble base — engraved.",
    description: "Three-piece executive desk set: pen, clock, and business-card holder mounted on a marble base. Engraved presentation plate.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 11,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:executive-desk-set",
    badges: ["Premium"],
  },
  {
    slug: "clear-acrylic-trophy",
    categorySlug: "corporate-awards",
    subcategorySlug: "acrylic-awards",
    title: "Clear Acrylic Standoff Trophy",
    shortDescription: "Modern clear acrylic with standoff hardware.",
    description: "Modern clear acrylic award mounted on standoff hardware over a black acrylic base. UV-printed full-color graphic.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["uv-print", "laser-engraving"],
    options: { Size: ["6×8", "8×10"] },
    heroPromptKey: "product:clear-acrylic-trophy",
  },
  {
    slug: "marble-clock-award",
    categorySlug: "corporate-awards",
    subcategorySlug: "clocks",
    title: "Marble Clock Award",
    shortDescription: "Marble desk clock with engraved plate.",
    description: "Polished marble desk clock with brass face and engraved presentation plate. Premium recognition.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 10,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black Marble", "Green Marble", "Burgundy Marble"] },
    heroPromptKey: "product:marble-clock-award",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PERSONALIZED GIFTS — additional formats
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "wood-hammer-engraved",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Engraved Wood Handle Hammer",
    shortDescription: "Walnut-handle hammer — engraved gift for trades/groomsmen.",
    description: "Solid wood-handle hammer with engraved presentation panel. Groomsman-gift, trades, or hardware-store gift staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:wood-hammer-engraved",
  },
  {
    slug: "leatherette-mouse-pad",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leatherette Mouse Pad",
    shortDescription: "Premium leatherette mouse pad — engraved monogram.",
    description: "Premium leatherette mouse pad with engraved monogram. Pairs with the leatherette desk-set series.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 6,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Wine/Gold", "Navy/Silver"] },
    heroPromptKey: "product:leatherette-mouse-pad",
  },
  {
    slug: "leatherette-business-card-holder",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leatherette Business Card Holder",
    shortDescription: "Slim leatherette card holder — engraved name.",
    description: "Slim pocket-style business card holder in leatherette. Engrave name and company on the front face.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 5,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Rustic", "Wine", "Navy"] },
    heroPromptKey: "product:leatherette-card-holder",
  },
  {
    slug: "leatherette-passport-cover",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leatherette Passport Cover",
    shortDescription: "Travel passport cover — engraved monogram.",
    description: "Standard-size passport cover in leatherette. Slips over a US passport. Engrave monogram for travel-club gifting.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 6,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Rustic", "Wine", "Navy"] },
    heroPromptKey: "product:leatherette-passport-cover",
  },
  {
    slug: "leatherette-checkbook-cover",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leatherette Checkbook Cover",
    shortDescription: "Standard checkbook cover — engraved monogram.",
    description: "Standard checkbook cover in leatherette with check duplicate slot. Engrave monogram for retiring-employee gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 6,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Rustic", "Wine", "Navy"] },
    heroPromptKey: "product:leatherette-checkbook-cover",
  },
  {
    slug: "leatherette-luggage-id-tag",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leatherette Luggage ID Tag",
    shortDescription: "Compact luggage ID tag — engraved with name and address.",
    description: "Compact luggage ID tag with hidden contact-info window. Engrave name on the front. Travel essential.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 5,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Rustic", "Wine", "Navy"] },
    heroPromptKey: "product:leatherette-luggage-id-tag",
  },
  {
    slug: "rustic-wood-sign",
    categorySlug: "personalized-gifts",
    subcategorySlug: "frames",
    title: "Rustic Wood Sign",
    shortDescription: "Engraved rustic wood sign — wedding, family name, established.",
    description: "Stained reclaimed-style wood sign with engraved family name and established year. Wedding and housewarming favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["12×16", "16×20", "20×30"] },
    heroPromptKey: "product:rustic-wood-sign",
  },
  {
    slug: "leather-watch-strap",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leather Watch Strap with Engraving",
    shortDescription: "Premium leather watch strap — engraved interior.",
    description: "Premium leather watch strap with engraved interior message. Discreet personalization for loved ones.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 11,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Brown", "Tan"], Width: ["18mm", "20mm", "22mm"] },
    heroPromptKey: "product:leather-watch-strap",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // BAGS — deeper coverage
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "messenger-bag",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bags",
    title: "Messenger Shoulder Bag",
    shortDescription: "Padded messenger bag with laptop sleeve — corporate.",
    description: "Padded messenger shoulder bag with 15\" laptop sleeve, accessory pockets, and adjustable strap. Embroidered front flap.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 12,
    decorationMethods: ["embroidery"],
    options: { Color: ["Black", "Charcoal", "Navy"] },
    heroPromptKey: "product:messenger-bag",
  },
  {
    slug: "fanny-pack",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bags",
    title: "Branded Fanny Pack",
    shortDescription: "Standard fanny pack with adjustable strap — festival giveaway.",
    description: "Standard polyester fanny pack with main and front zip pockets. Embroidered or heat-transferred front panel.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["embroidery", "heat-transfer"],
    options: { Color: ["Black", "Navy", "Royal", "Red", "Pink"] },
    heroPromptKey: "product:fanny-pack",
  },
  {
    slug: "garment-bag",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bags",
    title: "Garment Travel Bag",
    shortDescription: "Tri-fold garment bag — business-travel staple.",
    description: "Tri-fold garment bag with built-in shoe pocket and accessory compartment. Carry handles and shoulder strap.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 14,
    decorationMethods: ["embroidery"],
    options: { Color: ["Black", "Charcoal"] },
    heroPromptKey: "product:garment-bag",
  },
  {
    slug: "sling-bag-crossbody",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bags",
    title: "Crossbody Sling Bag",
    shortDescription: "One-strap crossbody sling — modern commute.",
    description: "Modern crossbody sling bag with single adjustable strap and front zip pocket. Embroidered front panel.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 11,
    decorationMethods: ["embroidery"],
    options: { Color: ["Black", "Charcoal", "Navy", "Olive"] },
    heroPromptKey: "product:sling-bag-crossbody",
  },
  {
    slug: "lunch-bag-insulated",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bags",
    title: "Insulated Lunch Bag",
    shortDescription: "Insulated lunch tote — corporate-wellness gift.",
    description: "Insulated lunch tote with zippered top, front utensil pocket, and shoulder strap. Embroidered or heat-transferred logo.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 10,
    decorationMethods: ["embroidery", "heat-transfer"],
    options: { Color: ["Black", "Navy", "Charcoal", "Burgundy"] },
    heroPromptKey: "product:lunch-bag-insulated",
  },
  {
    slug: "wine-tote-bag",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bags",
    title: "Insulated Wine Tote Bag",
    shortDescription: "Wine-bottle tote — picnic and gifting.",
    description: "Insulated tote that holds 2 bottles plus a corkscrew. Padded interior. Embroidered front panel.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 10,
    decorationMethods: ["embroidery"],
    options: { Color: ["Black", "Burgundy", "Navy"] },
    heroPromptKey: "product:wine-tote-bag",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // SPORTS / ACADEMIC AWARDS — additional sport variants
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "softball-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "medals",
    title: "Softball Medal",
    shortDescription: "2-inch softball insert medal — youth-league standard.",
    description: "Die-cast 2-inch medal with softball insert and team-color ribbon. Bulk-friendly for season-end.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:softball-medal",
  },
  {
    slug: "wrestling-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "medals",
    title: "Wrestling Medal",
    shortDescription: "2-inch wrestling insert medal — meet award.",
    description: "Die-cast wrestling medal, 2-inch, with neck ribbon. Standard for HS and middle-school meets.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:wrestling-medal",
  },
  {
    slug: "lacrosse-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "medals",
    title: "Lacrosse Medal",
    shortDescription: "2-inch lacrosse insert medal — youth-league.",
    description: "Die-cast lacrosse medal with neck ribbon. Standard for youth-league and tournament awards.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:lacrosse-medal",
  },
  {
    slug: "golf-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "medals",
    title: "Golf Medal",
    shortDescription: "2-inch golf insert medal — tournament award.",
    description: "Die-cast golf medal with neck ribbon. Tournament closest-to-pin and longest-drive favorites.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:golf-medal",
  },
  {
    slug: "resin-lacrosse-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Lacrosse Trophy",
    shortDescription: "Hand-painted lacrosse figure on a weighted base.",
    description: "Resin lacrosse figure on a weighted black base. Engraving plate, multiple sizes for graded tournament tiers.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["6\"", "8\"", "10\"", "12\""] },
    heroPromptKey: "product:resin-lacrosse",
  },
  {
    slug: "resin-soccer-female",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Female Soccer Trophy",
    shortDescription: "Female soccer figure — girls' league standard.",
    description: "Hand-painted female soccer figure on a weighted black base with engraving plate. Girls' youth-league tournament award.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["6\"", "8\"", "10\"", "12\""] },
    heroPromptKey: "product:resin-soccer-female",
  },
  {
    slug: "resin-cross-country-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Cross-Country Trophy",
    shortDescription: "Distance-runner figure on a weighted base.",
    description: "Resin distance-runner figure on a weighted base. Cross-country meet and 5K-fun-run award.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["6\"", "8\"", "10\"", "12\""] },
    heroPromptKey: "product:resin-cross-country",
  },
  {
    slug: "music-trophy-resin",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "academic-awards",
    title: "Music / Band Trophy",
    shortDescription: "Resin music figure on a weighted base.",
    description: "Resin music note or band figure on a weighted black base with engraved presentation plate. Year-end music recognition.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["6\"", "8\"", "10\""] },
    heroPromptKey: "product:music-trophy-resin",
  },
  {
    slug: "robotics-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "academic-awards",
    title: "Robotics / STEM Competition Trophy",
    shortDescription: "Modern resin robotics figure — FIRST and similar leagues.",
    description: "Resin robotics figure on a weighted base with engraving plate. FIRST, VEX, and other STEM-competition award.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["8\"", "10\"", "12\""] },
    heroPromptKey: "product:robotics-trophy",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // BULK BLANKS — additional staples
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "blank-baseball-caps-dozen",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-apparel",
    title: "Blank Baseball Caps — Dozen",
    shortDescription: "12 unstructured baseball caps — dozen pricing.",
    description: "Dozen of unstructured 6-panel baseball caps with adjustable strap. Mix solid colors. Stage for in-house decoration.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: [],
    options: { Color: ["Black", "Navy", "Khaki", "White", "Charcoal"] },
    heroPromptKey: "product:blank-baseball-caps-dozen",
  },
  {
    slug: "blank-aprons-bib-dozen",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-apparel",
    title: "Blank Bistro Aprons — Dozen",
    shortDescription: "12 short bistro waist aprons — server-style.",
    description: "Dozen of waist-tie bistro aprons with two front pockets. Restaurant-server staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: [],
    options: { Color: ["Black", "Khaki", "Burgundy", "Forest"] },
    heroPromptKey: "product:blank-bistro-aprons-dozen",
  },
  {
    slug: "blank-stainless-flasks-dozen",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-drinkware",
    title: "Blank Stainless Flasks — Dozen",
    shortDescription: "12 blank 6oz stainless flasks — engrave or resell.",
    description: "Dozen of standard 6oz stainless steel flasks. Single colorway per dozen. For in-house engraving or wholesale resale.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: [],
    options: { Color: ["Stainless", "Black", "Navy"] },
    heroPromptKey: "product:blank-flasks-dozen",
  },
  {
    slug: "blank-coasters-pack",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-awards-plaques",
    title: "Blank Leatherette Coasters — Pack (50 ct)",
    shortDescription: "50 blank leatherette coasters — engrave-ready.",
    description: "Pack of 50 blank leatherette coasters in a single colorway. Stage for in-house engraving or wholesale resale.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: [],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Wine/Gold"] },
    heroPromptKey: "product:blank-coasters-pack",
  },
  {
    slug: "blank-keychains-bulk",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-awards-plaques",
    title: "Blank Leatherette Keychains — Pack (100 ct)",
    shortDescription: "100 blank leatherette key tags — engrave or print.",
    description: "Pack of 100 blank leatherette key tags with split rings. Single colorway per pack.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: [],
    options: { Color: ["Black", "Rustic", "Wine", "Navy"] },
    heroPromptKey: "product:blank-keychains-bulk",
  },
  {
    slug: "blank-trophy-figures-bulk",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-awards-plaques",
    title: "Blank Trophy Figures — Box (24 ct)",
    shortDescription: "24 blank resin sport figures — assemble custom trophies.",
    description: "Box of 24 blank resin sport figures (mixed sports) for in-house trophy assembly. Pair with bases and engraving plates.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: [],
    options: { Sport: ["Soccer", "Basketball", "Baseball", "Football", "Mixed"] },
    heroPromptKey: "product:blank-trophy-figures",
  },
];
