import type { SampleProduct } from "./sample-products";

/**
 * Catalog expansion drawn from competitor catalogs:
 *   whitesquirrelmktg.com, printtales.com, catalog.companycasuals.com,
 *   premiercorporateawards.com, premierdrinkware.com, premiercustomcolor.com,
 *   premierpersonalizedgifts.com, premiersportawards.com, gapromotional.com.
 *
 * Pricing is left at `quote` status across the board — operator confirms
 * tier pricing on a per-SKU basis. The PDP handles quote-only items.
 *
 * Brand names are kept ONLY where the brand IS the spec customers search by
 * (Polar Camel, Bella+Canvas 3001 etc.). Anything ambiguous is genericized.
 */

export const importedProducts: SampleProduct[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // CUSTOM PRINTING — wide-format and signage gap fillers
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "foam-mounted-poster",
    categorySlug: "custom-printing",
    subcategorySlug: "foam-board-posters",
    title: "Foam-Mounted Poster",
    shortDescription: "3/16\" foam-core mounted poster — print and trim to any size.",
    description: "High-resolution poster mounted on rigid 3/16\" foam-core board. Trade shows, lobby displays, photo art. Single or double-sided.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: ["digital-print"],
    options: { Size: ["18×24", "24×36", "36×48", "Custom"], Sides: ["Single", "Double"] },
    heroPromptKey: "product:foam-mounted-poster",
  },
  {
    slug: "step-and-repeat-banner",
    categorySlug: "custom-printing",
    subcategorySlug: "step-and-repeat-banners",
    title: "Step & Repeat Backdrop Banner",
    shortDescription: "Red-carpet event backdrop — vinyl or fabric, full-color logo repeat.",
    description: "Classic step-and-repeat backdrop for galas, premieres, and brand activations. 8×8 or 8×10 standard, fabric or vinyl, ships flat or with a portable frame kit.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 6,
    decorationMethods: ["digital-print"],
    options: { Size: ["8×8", "8×10", "10×8", "Custom"], Material: ["13oz Vinyl", "Polyester Fabric"], Frame: ["No frame", "Pop-up frame kit"] },
    heroPromptKey: "product:step-and-repeat-banner",
    badges: ["Event Favorite"],
  },
  {
    slug: "x-stand-banner",
    categorySlug: "custom-printing",
    subcategorySlug: "x-stands",
    title: "X-Stand Banner",
    shortDescription: "24×63 lightweight X-frame banner — two-minute setup.",
    description: "Lightweight X-frame banner stand for lobbies, conferences, retail. Tension-mounted vinyl, two-minute setup, includes carry bag.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: ["digital-print"],
    options: { Size: ["24×63", "32×72"] },
    heroPromptKey: "product:x-stand-banner",
  },
  {
    slug: "roll-up-banner-stand",
    categorySlug: "custom-printing",
    subcategorySlug: "roll-up-signs",
    title: "Roll-Up Banner Sign",
    shortDescription: "33×80 retractable roll-up — stows in its own base.",
    description: "Standard 33×80 retractable roll-up banner. Aluminum base with built-in storage, full-color printed graphic, padded carry bag included.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: ["digital-print"],
    options: { Width: ["33\"", "39\"", "47\""] },
    heroPromptKey: "product:roll-up-banner-sign",
  },
  {
    slug: "a-frame-sidewalk-sign",
    categorySlug: "custom-printing",
    subcategorySlug: "a-frames",
    title: "A-Frame Sidewalk Sign",
    shortDescription: "Heavy-duty plastic A-frame with double-sided printed inserts.",
    description: "All-weather plastic A-frame with two replaceable printed graphic inserts. Restaurants, retail, real-estate open houses.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["digital-print"],
    options: { Size: ["24×36", "24×48"] },
    heroPromptKey: "product:a-frame-sign",
  },
  {
    slug: "table-cover-printed",
    categorySlug: "custom-printing",
    subcategorySlug: "table-covers",
    title: "Printed Table Cover",
    shortDescription: "6ft or 8ft fitted table throw — full-color polyester, dye-sub.",
    description: "Dye-sublimated polyester table cover, full-color with logo, sized to fit standard 6ft or 8ft event tables. Stretch-fit or open-back styles.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["sublimation"],
    options: { Size: ["6ft", "8ft"], Style: ["Open-back", "Closed-back", "Stretch-fit"] },
    heroPromptKey: "product:table-cover",
  },
  {
    slug: "tradeshow-backdrop-tension",
    categorySlug: "custom-printing",
    subcategorySlug: "trade-show-backdrops",
    title: "Tension-Fabric Trade-Show Backdrop",
    shortDescription: "10ft pillowcase backdrop — wrinkle-free fabric on aluminum frame.",
    description: "Wall-style backdrop for trade-show booths. Tension-stretched dye-sub fabric over a tool-free aluminum frame. Packs into a wheeled case.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["sublimation"],
    options: { Size: ["8ft", "10ft", "20ft"], Style: ["Straight", "Curved"] },
    heroPromptKey: "product:tradeshow-backdrop",
  },
  {
    slug: "heavy-business-cards",
    categorySlug: "custom-printing",
    subcategorySlug: "business-cards",
    title: "Heavy 32pt Business Cards",
    shortDescription: "Premium 32pt cardstock with painted edge options.",
    description: "Hefty 32pt uncoated cards with optional painted edges in black, crimson, navy, or kraft. Makes a tactile first impression.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 7,
    decorationMethods: ["offset-print", "foil"],
    options: { Quantity: ["250", "500", "1000", "2500"], "Painted edge": ["None", "Black", "Crimson", "Navy", "Kraft"] },
    heroPromptKey: "product:heavy-business-cards",
    badges: ["Premium"],
  },
  {
    slug: "linen-business-cards",
    categorySlug: "custom-printing",
    subcategorySlug: "business-cards",
    title: "Linen-Finish Business Cards",
    shortDescription: "Subtle linen texture — 100lb cover, full color.",
    description: "Refined linen-textured cardstock that takes ink beautifully. Great for legal, real estate, accounting, and consulting brands.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 5,
    decorationMethods: ["offset-print"],
    options: { Quantity: ["250", "500", "1000", "2500"] },
    heroPromptKey: "product:linen-business-cards",
  },
  {
    slug: "silk-laminated-business-cards",
    categorySlug: "custom-printing",
    subcategorySlug: "business-cards",
    title: "Silk-Laminated Business Cards",
    shortDescription: "Soft-touch silk lamination — luxe finish, durable surface.",
    description: "Silk-laminated 16pt cards with a soft-touch hand and premium feel. Optional spot UV or foil accents.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 7,
    decorationMethods: ["offset-print", "uv-gloss", "foil"],
    options: { Quantity: ["250", "500", "1000", "2500"] },
    heroPromptKey: "product:silk-laminated-business-cards",
  },
  {
    slug: "bi-fold-restaurant-menu",
    categorySlug: "custom-printing",
    subcategorySlug: "menus",
    title: "Bi-Fold Restaurant Menu",
    shortDescription: "100lb gloss text or 14pt cover — laminated optional.",
    description: "Folded restaurant menus on 100lb gloss text or laminated 14pt cover for spill resistance. Includes kids menus, specials, take-out.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 5,
    decorationMethods: ["digital-print", "offset-print"],
    options: { Size: ["8.5×11", "8.5×14", "11×17"], Stock: ["100lb Gloss Text", "14pt Cover Laminated"] },
    heroPromptKey: "product:bi-fold-menu",
  },
  {
    slug: "take-out-menus",
    categorySlug: "custom-printing",
    subcategorySlug: "menus",
    title: "Take-Out Menus",
    shortDescription: "Unfolded full-color take-out menus on light text stock.",
    description: "Single-sheet take-out menus printed full color on 70lb or 80lb text. Door-hang style or standard distribution.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 500,
    leadTimeDays: 4,
    decorationMethods: ["digital-print"],
    heroPromptKey: "product:take-out-menus",
  },
  {
    slug: "carbonless-2part-form",
    categorySlug: "custom-printing",
    subcategorySlug: "carbonless-forms",
    title: "2-Part Carbonless Forms",
    shortDescription: "White/canary 2-part NCR forms — padded or booked.",
    description: "Standard 2-part NCR carbonless forms in white/canary. Choose loose padded sets or wire-bound books.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 7,
    decorationMethods: ["offset-print"],
    options: { Format: ["Padded sets", "Booked"], Size: ["5.5×8.5", "8.5×11"] },
    heroPromptKey: "product:carbonless-2part",
  },
  {
    slug: "carbonless-3part-form",
    categorySlug: "custom-printing",
    subcategorySlug: "carbonless-forms",
    title: "3-Part Carbonless Forms",
    shortDescription: "White/canary/pink 3-part — for invoices and POs.",
    description: "Three-part NCR forms in white/canary/pink for invoicing, work orders, and POs. Numbered or non-numbered.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 8,
    decorationMethods: ["offset-print"],
    options: { Format: ["Padded sets", "Booked"], Numbered: ["Yes", "No"] },
    heroPromptKey: "product:carbonless-3part",
  },
  {
    slug: "feather-flag-single-side",
    categorySlug: "custom-printing",
    subcategorySlug: "feather-flags",
    title: "Feather Flag (Single-Sided)",
    shortDescription: "11.5ft outdoor feather flag with ground stake or cross base.",
    description: "Tall outdoor feather flag, single-sided polyester print, with choice of ground spike or cross-base hardware.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["sublimation"],
    options: { Size: ["8.5ft", "11.5ft", "14ft"], Hardware: ["Ground Spike", "Cross Base", "Wall Mount"] },
    heroPromptKey: "product:feather-flag-single",
  },
  {
    slug: "magnet-calendar",
    categorySlug: "custom-printing",
    subcategorySlug: "magnet-calendars",
    title: "Refrigerator Magnet Calendar",
    shortDescription: "Full-year magnet calendar — real-estate and restaurant favorite.",
    description: "Glossy 4×7 or 4×9 magnetic calendar printed on heavy magnet stock. Imprint your logo, business hours, and contact info.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 6,
    decorationMethods: ["digital-print"],
    options: { Size: ["4×7", "4×9"] },
    heroPromptKey: "product:magnet-calendar",
  },
  {
    slug: "car-door-magnet-pair",
    categorySlug: "custom-printing",
    subcategorySlug: "car-door-magnets",
    title: "Car Door Magnet Pair",
    shortDescription: "Heavy-duty 30mil car magnets — sold in pairs.",
    description: "Heavy-duty 30mil rounded-corner car magnets in standard or custom sizes. Sold as a matched left/right pair.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["digital-print"],
    options: { Size: ["12×18", "18×24", "24×12", "Custom"] },
    heroPromptKey: "product:car-door-magnet-pair",
  },
  {
    slug: "table-tents",
    categorySlug: "custom-printing",
    subcategorySlug: "table-tents",
    title: "Table Tents",
    shortDescription: "Folded restaurant table-top tents — full color, 14pt cover.",
    description: "Pre-scored folded table tents for restaurant specials, daily promos, and event tables. 14pt cover, full color all sides.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 5,
    decorationMethods: ["digital-print"],
    options: { Size: ["4×6", "5×7", "Custom"] },
    heroPromptKey: "product:table-tents",
  },
  {
    slug: "door-hangers",
    categorySlug: "custom-printing",
    subcategorySlug: "door-hangers",
    title: "Door Hangers",
    shortDescription: "Die-cut door hangers — perfect for canvassing routes.",
    description: "Die-cut 4.25×11 door hangers on 14pt or 100lb gloss. Real estate, neighborhood services, lawn care.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 5,
    decorationMethods: ["digital-print"],
    heroPromptKey: "product:door-hangers",
  },
  {
    slug: "holiday-greeting-cards",
    categorySlug: "custom-printing",
    subcategorySlug: "holiday-cards",
    title: "Holiday Greeting Cards",
    shortDescription: "Folded 5×7 holiday cards with envelopes — foil optional.",
    description: "Folded 5×7 holiday cards on 14pt cover, white envelopes included. Foil accents available for premium look.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 7,
    decorationMethods: ["digital-print", "foil"],
    options: { Quantity: ["50", "100", "250", "500"], Foil: ["No", "Gold", "Silver", "Rose Gold"] },
    heroPromptKey: "product:holiday-cards",
  },
  {
    slug: "address-labels-roll",
    categorySlug: "custom-printing",
    subcategorySlug: "address-labels",
    title: "Address Label Rolls",
    shortDescription: "Self-adhesive address labels — printed on rolls or sheets.",
    description: "Custom return-address or shipping labels printed on roll stock or 8.5×11 sheets. Specify size, adhesive, and quantity.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 500,
    leadTimeDays: 5,
    decorationMethods: ["digital-print"],
    options: { Size: ['1.5"×0.5"', '2.625"×1"', '4"×6"', "Custom"], Format: ["Roll", "Sheet"] },
    heroPromptKey: "product:address-labels",
  },
  {
    slug: "vinyl-lettering-storefront",
    categorySlug: "custom-printing",
    subcategorySlug: "vinyl-lettering",
    title: "Storefront Vinyl Lettering",
    shortDescription: "Cut-vinyl lettering for windows, vehicles, and walls.",
    description: "Premium 6-year outdoor cut-vinyl lettering. Choose colors, font, and size — we deliver pre-spaced with transfer tape.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["digital-print"],
    options: { Color: ["Black", "White", "Crimson", "Navy", "Gold", "Custom"] },
    heroPromptKey: "product:vinyl-lettering",
  },
  {
    slug: "fat-head-graduation",
    categorySlug: "custom-printing",
    subcategorySlug: "fat-heads",
    title: "Graduation Fat Head",
    shortDescription: "Oversized cardboard cutout — graduation parties, sports events.",
    description: "Life-sized cutout printed on rigid foam or coroplast. Custom photo upload, perfect for graduations, retirements, or sports days.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 6,
    decorationMethods: ["digital-print"],
    options: { Size: ["24\"", "36\"", "48\"", "Lifesize"] },
    heroPromptKey: "product:fat-head-graduation",
  },
  {
    slug: "graduation-yard-sign",
    categorySlug: "custom-printing",
    subcategorySlug: "graduation-yard-signs",
    title: "Graduation Yard Sign",
    shortDescription: "18×24 corrugated yard sign — name, photo, school colors.",
    description: "Custom graduation yard signs with name, photo, school logo, and the year. Includes H-stake. Class of 2026 ready.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: ["digital-print"],
    options: { Size: ["18×24", "24×36"], Stake: ["H-Stake", "Step Stake"] },
    heroPromptKey: "product:graduation-yard-sign",
    badges: ["Spring Favorite"],
  },
  {
    slug: "uv-dtf-transfer-custom",
    categorySlug: "custom-printing",
    subcategorySlug: "uv-dtf-transfers",
    title: "Custom UV DTF Transfer",
    shortDescription: "Apply to glass, metal, plastic — no heat press needed.",
    description: "UV DTF transfers stick to almost any hard surface — drinkware, candle jars, signage, packaging. Peel and apply, no heat press required.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: ["uv-print"],
    options: { Size: ["3×3", "4×4", "Sheet 8.5×11", "Custom"] },
    heroPromptKey: "product:uv-dtf-transfer",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // APPAREL & HEADWEAR — broaden the catalog
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "tri-blend-tee",
    categorySlug: "apparel-headwear",
    subcategorySlug: "t-shirts",
    title: "Tri-Blend Crew Tee",
    shortDescription: "Soft tri-blend cotton/poly/rayon — wears like a vintage favorite.",
    description: "Tri-blend cotton/poly/rayon crew with a softer drape and heathered look. Pairs nicely with screen print and DTF.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["screen-print", "dtf", "embroidery"],
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL", "3XL"], Color: ["Heather Grey", "Heather Black", "Heather Navy", "Heather Forest", "Heather Maroon"] },
    heroPromptKey: "product:tri-blend-tee",
  },
  {
    slug: "long-sleeve-tee",
    categorySlug: "apparel-headwear",
    subcategorySlug: "t-shirts",
    title: "Long Sleeve Tee",
    shortDescription: "Heavyweight long-sleeve cotton — fall/winter staple.",
    description: "Mid-weight 100% cotton long-sleeve tee. Front, back, and sleeve decoration zones. Bulk-priced for teams.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 8,
    decorationMethods: ["screen-print", "dtf", "embroidery"],
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL"] },
    heroPromptKey: "product:long-sleeve-tee",
  },
  {
    slug: "performance-polo",
    categorySlug: "apparel-headwear",
    subcategorySlug: "polos-knits",
    title: "Performance Polo",
    shortDescription: "Moisture-wicking performance polo — corporate-uniform ready.",
    description: "Snag-resistant moisture-wicking polo. Embroiders cleanly, holds color through wash cycles. Tall sizes available.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 8,
    decorationMethods: ["embroidery", "heat-transfer"],
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "Tall"], Color: ["Black", "Navy", "White", "Royal", "Red"] },
    heroPromptKey: "product:performance-polo",
  },
  {
    slug: "easy-care-polo",
    categorySlug: "apparel-headwear",
    subcategorySlug: "polos-knits",
    title: "Easy-Care Cotton/Poly Polo",
    shortDescription: "Wrinkle-resistant cotton/poly blend — wash and wear.",
    description: "Classic cotton/poly polo with knit collar and pearl buttons. Easy-care wash, no shrink. The everyday workhorse.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["embroidery", "heat-transfer"],
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL"], Color: ["White", "Black", "Navy", "Hunter", "Burgundy", "Royal"] },
    heroPromptKey: "product:easy-care-polo",
  },
  {
    slug: "quarter-zip-pullover",
    categorySlug: "apparel-headwear",
    subcategorySlug: "sweatshirts-fleece",
    title: "Quarter-Zip Performance Pullover",
    shortDescription: "Lightweight 1/4-zip — corporate teams and golf events.",
    description: "Brushed-back performance fabric in a flattering 1/4-zip cut. Embroiders well at the left chest. A corporate-uniform staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["embroidery"],
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"], Color: ["Black", "Navy", "Steel Grey", "Maroon", "Hunter"] },
    heroPromptKey: "product:quarter-zip-pullover",
  },
  {
    slug: "full-zip-fleece-jacket",
    categorySlug: "apparel-headwear",
    subcategorySlug: "outerwear",
    title: "Full-Zip Fleece Jacket",
    shortDescription: "Mid-weight anti-pill fleece — soft hand, durable wear.",
    description: "Full-zip mid-weight fleece jacket with zippered side pockets. Embroiders crisp logos at the left chest or back yoke.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 6,
    leadTimeDays: 9,
    decorationMethods: ["embroidery", "heat-transfer"],
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"], Color: ["Black", "Navy", "Charcoal", "Forest", "Maroon"] },
    heroPromptKey: "product:fleece-jacket",
  },
  {
    slug: "soft-shell-jacket",
    categorySlug: "apparel-headwear",
    subcategorySlug: "outerwear",
    title: "Soft Shell Jacket",
    shortDescription: "Wind- and water-resistant soft shell — corporate-jacket favorite.",
    description: "Three-layer bonded soft shell with wind- and water-resistance. Premium corporate-jacket feel that embroiders cleanly.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 6,
    leadTimeDays: 11,
    decorationMethods: ["embroidery"],
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"], Color: ["Black", "Navy", "Steel Grey", "Maroon"] },
    heroPromptKey: "product:soft-shell-jacket",
    badges: ["Premium"],
  },
  {
    slug: "puffer-vest",
    categorySlug: "apparel-headwear",
    subcategorySlug: "outerwear",
    title: "Insulated Puffer Vest",
    shortDescription: "Lightweight insulated vest — fall/winter corporate gifting.",
    description: "Lightweight quilted vest with synthetic insulation. Layers under a jacket or wears solo. Great for fall/winter corporate gifting.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 6,
    leadTimeDays: 10,
    decorationMethods: ["embroidery"],
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL"], Color: ["Black", "Navy", "Charcoal", "Burgundy"] },
    heroPromptKey: "product:puffer-vest",
  },
  {
    slug: "oxford-dress-shirt",
    categorySlug: "apparel-headwear",
    subcategorySlug: "woven-dress-shirts",
    title: "Easy-Care Oxford Dress Shirt",
    shortDescription: "Wrinkle-resistant oxford — corporate-uniform classic.",
    description: "Wrinkle-resistant cotton/poly oxford in standard fits. Long sleeve, button-down collar, pencil pocket. Embroidered or printed left chest.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 6,
    leadTimeDays: 9,
    decorationMethods: ["embroidery"],
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL", "Tall"], Color: ["White", "Light Blue", "French Blue", "Charcoal"] },
    heroPromptKey: "product:oxford-shirt",
  },
  {
    slug: "denim-shirt",
    categorySlug: "apparel-headwear",
    subcategorySlug: "woven-dress-shirts",
    title: "Denim Work Shirt",
    shortDescription: "Stonewashed denim long-sleeve — workwear with a clean drape.",
    description: "Stonewashed denim long-sleeve shirt with double-button cuffs. Embroidery and patch decoration both pop on this classic.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 6,
    leadTimeDays: 9,
    decorationMethods: ["embroidery"],
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL"] },
    heroPromptKey: "product:denim-shirt",
  },
  {
    slug: "flex-fit-cap",
    categorySlug: "apparel-headwear",
    subcategorySlug: "caps",
    title: "Flex-Fit Cap",
    shortDescription: "Stretch-fit flex cap — clean structured silhouette.",
    description: "Six-panel structured flex-fit cap. Embroiders crisp 3D logos at the front center, with options for flat or curved bills.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["embroidery", "3d-embroidery"],
    options: { Size: ["S/M", "L/XL"], Color: ["Black", "Navy", "Charcoal", "Heather Grey"] },
    heroPromptKey: "product:flex-fit-cap",
  },
  {
    slug: "knit-beanie",
    categorySlug: "apparel-headwear",
    subcategorySlug: "beanies-visors",
    title: "Knit Beanie with Cuff",
    shortDescription: "Acrylic ribbed beanie — embroidered or patch-applied logo.",
    description: "Classic ribbed-knit cuffed beanie. Embroidered front-center logo or leather patch. Great cool-weather giveaway.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["embroidery", "leather-patch"],
    options: { Color: ["Black", "Charcoal", "Navy", "Burgundy", "Forest", "Heather Grey"] },
    heroPromptKey: "product:knit-beanie",
  },
  {
    slug: "sun-visor",
    categorySlug: "apparel-headwear",
    subcategorySlug: "beanies-visors",
    title: "Sport Sun Visor",
    shortDescription: "Performance visor — golf days, summer events.",
    description: "Performance moisture-wicking sun visor with pre-curved bill. Embroidered or screen-printed front center logo.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["embroidery"],
    options: { Color: ["White", "Black", "Navy", "Red", "Royal"] },
    heroPromptKey: "product:sun-visor",
  },
  {
    slug: "drawstring-backpack",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bags",
    title: "Drawstring Cinch Backpack",
    shortDescription: "Lightweight cinch backpack — schools, conferences, swag bags.",
    description: "Lightweight polyester cinch sack with drawstring closure. School-event and conference-swag favorite, screen-prints in bold colors.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 6,
    decorationMethods: ["screen-print", "heat-transfer"],
    options: { Color: ["Black", "Royal", "Red", "Forest", "Yellow", "Pink"] },
    heroPromptKey: "product:drawstring-backpack",
  },
  {
    slug: "laptop-backpack",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bags",
    title: "Laptop Commuter Backpack",
    shortDescription: "Padded 15\" laptop sleeve — corporate gift staple.",
    description: "Tech-organizer commuter backpack with padded 15\" laptop sleeve, USB pass-through, and water-bottle pockets. Embroidered logo.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 11,
    decorationMethods: ["embroidery", "heat-transfer"],
    options: { Color: ["Black", "Charcoal", "Navy"] },
    heroPromptKey: "product:laptop-backpack",
    badges: ["Corporate Gift"],
  },
  {
    slug: "duffel-bag",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bags",
    title: "Sport Duffel Bag",
    shortDescription: "20\" team duffel — embroidered or screen-printed logo panel.",
    description: "Heavy-duty 20\" duffel with adjustable shoulder strap and end pocket. Decorate the side panel with logo or team name.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 10,
    decorationMethods: ["embroidery", "screen-print"],
    options: { Color: ["Black", "Navy", "Royal", "Red"] },
    heroPromptKey: "product:duffel-bag",
  },
  {
    slug: "chef-apron",
    categorySlug: "apparel-headwear",
    subcategorySlug: "aprons",
    title: "Bib Apron",
    shortDescription: "Heavy twill chef apron — restaurants, bakeries, baristas.",
    description: "Adjustable-neck heavy twill bib apron with two front pockets. Embroidered chest logo for staff uniforms.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 8,
    decorationMethods: ["embroidery", "screen-print"],
    options: { Color: ["Black", "Charcoal", "Khaki", "White"] },
    heroPromptKey: "product:chef-apron",
  },
  {
    slug: "scrub-top",
    categorySlug: "apparel-headwear",
    subcategorySlug: "scrubs-lab-coats",
    title: "Performance Scrub Top",
    shortDescription: "Anti-microbial scrub top — clinics, dental, vet, doctor's offices.",
    description: "Soft anti-microbial scrub top with chest pocket and side vents. Embroidered name and credentials on left chest.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 6,
    leadTimeDays: 9,
    decorationMethods: ["embroidery"],
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL", "3XL"], Color: ["Caribbean Blue", "Navy", "Wine", "Hunter", "Black", "Pewter"] },
    heroPromptKey: "product:scrub-top",
    badges: ["Clinic Favorite"],
  },
  {
    slug: "lab-coat",
    categorySlug: "apparel-headwear",
    subcategorySlug: "scrubs-lab-coats",
    title: "Long Lab Coat",
    shortDescription: "Classic 41\" lab coat — embroidered name + credentials.",
    description: "Traditional 41\" white lab coat with notched lapel, three pockets, and side slits. Personalized name and credentials at left chest.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["embroidery"],
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL"] },
    heroPromptKey: "product:lab-coat",
  },
  {
    slug: "hi-vis-safety-vest",
    categorySlug: "apparel-headwear",
    subcategorySlug: "personal-protection",
    title: "Hi-Vis Safety Vest (ANSI Class 2)",
    shortDescription: "ANSI Class 2 hi-vis vest — heat-transfer logo, hook-and-loop closure.",
    description: "ANSI Class 2 hi-vis safety vest in lime or orange with reflective tape. Heat-transfer or screen-print company logo on the back.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["heat-transfer", "screen-print"],
    options: { Size: ["M", "L", "XL", "2XL", "3XL", "4XL"], Color: ["Hi-Vis Lime", "Hi-Vis Orange"] },
    heroPromptKey: "product:hi-vis-vest",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CORPORATE AWARDS — broaden the catalog
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "rosewood-piano-plaque",
    categorySlug: "corporate-awards",
    subcategorySlug: "plaques",
    title: "Rosewood Piano-Finish Plaque",
    shortDescription: "Lustrous rosewood piano finish — engraved brass plate.",
    description: "Rich rosewood piano-finish plaque with brass engraving plate. Premium recognition for retirement, top-of-class, or service awards.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["8×10", "9×12", "10.5×13"] },
    heroPromptKey: "product:rosewood-piano-plaque",
  },
  {
    slug: "leatherette-plaque",
    categorySlug: "corporate-awards",
    subcategorySlug: "plaques",
    title: "Leatherette Plaque",
    shortDescription: "Modern leatherette-on-MDF plaque — laser engraves cream.",
    description: "Contemporary leatherette plaque with deep cream engrave. Lighter than wood and ships in five colors.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["7×9", "8×10", "9×12"], Color: ["Black/Silver", "Rustic/Gold", "Gray/Black", "Blue/Silver", "Wine/Gold"] },
    heroPromptKey: "product:leatherette-plaque",
  },
  {
    slug: "perpetual-plaque",
    categorySlug: "corporate-awards",
    subcategorySlug: "perpetual-plaques",
    title: "Perpetual Recognition Plaque",
    shortDescription: "Wall-mounted perpetual plaque with annual add-on plates.",
    description: "Long-form recognition plaque with header engraving and rows of small annual plates. Perfect for years-of-service or champions-of-the-year programs.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 12,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["12×15 (8 plates)", "16×20 (16 plates)", "20×26 (24 plates)"] },
    heroPromptKey: "product:perpetual-plaque",
    badges: ["Long-Term Recognition"],
  },
  {
    slug: "crystal-pillar-award",
    categorySlug: "corporate-awards",
    subcategorySlug: "crystal-awards",
    title: "Crystal Pillar Award",
    shortDescription: "Optical-crystal pillar — sand-etched front face.",
    description: "Optical crystal pillar with sand-etched recognition text on the front face. Heavy and timeless.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 10,
    decorationMethods: ["laser-engraving", "sand-etch"],
    options: { Size: ["7\"", "9\"", "11\""] },
    heroPromptKey: "product:crystal-pillar",
  },
  {
    slug: "crystal-flame-award",
    categorySlug: "corporate-awards",
    subcategorySlug: "crystal-awards",
    title: "Crystal Flame Award",
    shortDescription: "Sculpted crystal flame on a black base — annual top performer.",
    description: "Sculpted optical-crystal flame mounted on a polished black base. Front face engraves cleanly. Top-performer favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 11,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["8\"", "10\"", "12\""] },
    heroPromptKey: "product:crystal-flame",
  },
  {
    slug: "art-glass-sculpture",
    categorySlug: "corporate-awards",
    subcategorySlug: "glass-awards",
    title: "Hand-Blown Art Glass Sculpture",
    shortDescription: "One-of-a-kind blown-glass piece — premium leadership awards.",
    description: "Hand-blown art-glass sculpture mounted on a polished base. Each piece is unique. Engraved presentation plate.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 18,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:art-glass-sculpture",
    badges: ["Premium"],
  },
  {
    slug: "eagle-sculpture-award",
    categorySlug: "corporate-awards",
    subcategorySlug: "desk-pieces",
    title: "Eagle Sculpture Award",
    shortDescription: "Cast eagle on a marble base — leadership and excellence.",
    description: "Cast metal eagle in mid-flight on a polished marble base. Engraved plate for recipient name and date.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 12,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["10\"", "13\""] },
    heroPromptKey: "product:eagle-sculpture",
  },
  {
    slug: "star-acrylic-award",
    categorySlug: "corporate-awards",
    subcategorySlug: "acrylic-awards",
    title: "Star Acrylic Award",
    shortDescription: "1\" thick star-cut acrylic — full-color UV print.",
    description: "Bevel-cut acrylic star with full-color UV print and laser-engraved presentation text on the reverse.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 8,
    decorationMethods: ["uv-print", "laser-engraving"],
    options: { Size: ["7\"", "9\""] },
    heroPromptKey: "product:star-acrylic-award",
  },
  {
    slug: "wall-clock-award",
    categorySlug: "corporate-awards",
    subcategorySlug: "clocks",
    title: "Engraved Wall Clock",
    shortDescription: "Round walnut wall clock — engraved center recognition.",
    description: "Round walnut wall clock with brushed brass face. Engraved presentation text encircles the dial. Quartz movement.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["12\"", "14\""] },
    heroPromptKey: "product:wall-clock-award",
  },
  {
    slug: "engraved-gavel-set",
    categorySlug: "corporate-awards",
    subcategorySlug: "gavels",
    title: "Engraved Gavel Set",
    shortDescription: "Walnut gavel and sound block — engraved brass plate.",
    description: "Solid walnut gavel paired with a matched sound block, mounted on a presentation board. Brass plate engraved with recipient details.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 11,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:engraved-gavel",
  },
  {
    slug: "name-plate-desk",
    categorySlug: "corporate-awards",
    subcategorySlug: "name-plates",
    title: "Engraved Desk Name Plate",
    shortDescription: "Walnut or rosewood name plate — engraved with title.",
    description: "Classic desk name plate in walnut or rosewood with brass plate engraved with name and title. Pair with a card holder.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 6,
    decorationMethods: ["laser-engraving"],
    options: { Wood: ["Walnut", "Rosewood"], Style: ["Wedge", "Flat"] },
    heroPromptKey: "product:name-plate-desk",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // DRINKWARE — broaden the catalog
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "polar-camel-30oz-tumbler",
    categorySlug: "drinkware",
    subcategorySlug: "polar-camel",
    title: "Polar Camel 30oz Vacuum Tumbler",
    shortDescription: "Larger 30oz double-wall stainless — laser engraves silver.",
    description: "Double-wall vacuum-insulated 30oz stainless tumbler. Laser engraving reveals a clean silver mark beneath the powder coat.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving", "uv-print"],
    options: { Color: ["Black", "White", "Navy", "Sage", "Mauve", "Stainless", "Rose Gold"] },
    heroPromptKey: "product:polar-camel-30oz",
  },
  {
    slug: "polar-camel-10oz-tumbler",
    categorySlug: "drinkware",
    subcategorySlug: "polar-camel",
    title: "Polar Camel 10oz Lowball",
    shortDescription: "Compact 10oz powder-coated lowball — wedding favor classic.",
    description: "Stocky 10oz lowball with vacuum insulation. Frequently chosen as a wedding favor or premium event giveaway.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Sage", "Navy", "White", "Rose Gold"] },
    heroPromptKey: "product:polar-camel-10oz",
  },
  {
    slug: "polar-camel-22oz-skinny",
    categorySlug: "drinkware",
    subcategorySlug: "polar-camel",
    title: "Polar Camel 22oz Skinny Tumbler",
    shortDescription: "Slim 22oz skinny — fits in cup holders, holds your coffee all morning.",
    description: "Slim-profile 22oz skinny tumbler that fits standard cup holders. Vacuum-insulated stainless that engraves cleanly.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Stainless", "Navy", "Rose Gold", "Sage"] },
    heroPromptKey: "product:polar-camel-22oz-skinny",
  },
  {
    slug: "polar-camel-40oz-tumbler",
    categorySlug: "drinkware",
    subcategorySlug: "40oz-tumblers",
    title: "Polar Camel 40oz Travel Tumbler",
    shortDescription: "Massive 40oz with handle and straw lid — keeps ice all day.",
    description: "Trending 40oz vacuum-insulated tumbler with carry handle, straw lid, and powder-coat finish. Engraves to a clean silver.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Sage", "Charcoal", "Stainless", "Rose Gold", "Mauve"] },
    heroPromptKey: "product:polar-camel-40oz",
    badges: ["Trending"],
  },
  {
    slug: "stainless-water-bottle-32oz",
    categorySlug: "drinkware",
    subcategorySlug: "water-bottles",
    title: "32oz Stainless Water Bottle",
    shortDescription: "Vacuum-insulated 32oz water bottle — gym, hike, classroom.",
    description: "Double-wall vacuum-insulated 32oz water bottle with leak-proof screw cap. Laser engraves to a clean silver tone.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving", "uv-print"],
    options: { Color: ["Stainless", "Black", "Navy", "Sage", "White"] },
    heroPromptKey: "product:water-bottle-32oz",
  },
  {
    slug: "travel-mug-16oz",
    categorySlug: "drinkware",
    subcategorySlug: "mugs",
    title: "16oz Travel Mug",
    shortDescription: "Insulated 16oz travel mug with flip-lid — commute-ready.",
    description: "Stainless travel mug with vacuum insulation and a flip-lid that's actually leak-tight. Daily-driver coffee staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving", "uv-print"],
    options: { Color: ["Black", "Stainless", "Navy", "Sage"] },
    heroPromptKey: "product:travel-mug-16oz",
  },
  {
    slug: "wine-tumbler-12oz",
    categorySlug: "drinkware",
    subcategorySlug: "wine-sets",
    title: "12oz Stemless Wine Tumbler",
    shortDescription: "Insulated stemless wine tumbler — engraved monogram or date.",
    description: "Double-wall stainless stemless wine tumbler. Wedding-favor and bridesmaid-gift favorite. Laser engraving holds beautifully.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Stainless", "Rose Gold", "Black", "Sage", "Mauve"] },
    heroPromptKey: "product:wine-tumbler-12oz",
  },
  {
    slug: "leatherette-flask-set",
    categorySlug: "drinkware",
    subcategorySlug: "flasks",
    title: "Leatherette Flask Gift Set",
    shortDescription: "6oz leatherette-wrapped flask + 4 shot cups + funnel — gift box.",
    description: "Premium 6oz leatherette-wrapped flask with four matching shot cups and a small funnel, all in a fitted gift box. Engraved monogram.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Wine/Gold", "Navy/Silver"] },
    heroPromptKey: "product:leatherette-flask-set",
  },
  {
    slug: "growler-64oz",
    categorySlug: "drinkware",
    subcategorySlug: "growlers",
    title: "64oz Stainless Growler",
    shortDescription: "Big-batch growler — brewery, taproom, beer-club gift.",
    description: "Double-wall vacuum-insulated 64oz growler with screw lid. Engraves cleanly with brewery logos and bar marks.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Stainless"] },
    heroPromptKey: "product:growler-64oz",
  },
  {
    slug: "shaker-bottle-26oz",
    categorySlug: "drinkware",
    subcategorySlug: "shaker-bottles",
    title: "26oz Protein Shaker Bottle",
    shortDescription: "BPA-free shaker with whisk ball — gym promo favorite.",
    description: "Shatter-proof BPA-free shaker bottle with stainless whisk ball. Print full color on the body for fitness brand swag.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 6,
    decorationMethods: ["uv-print"],
    options: { Color: ["Clear", "Smoke", "Frost"] },
    heroPromptKey: "product:shaker-bottle-26oz",
  },
  {
    slug: "leatherette-coaster-set",
    categorySlug: "drinkware",
    subcategorySlug: "coasters",
    title: "Leatherette Coaster Set (6-pack)",
    shortDescription: "Six leatherette coasters with holder — laser engraved.",
    description: "Six round leatherette coasters in a matching holder. Engraves cleanly with monograms or logos. Wedding and corporate-gift staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Wine/Gold", "Navy/Silver"] },
    heroPromptKey: "product:leatherette-coasters",
  },
  {
    slug: "leatherette-bottle-opener",
    categorySlug: "drinkware",
    subcategorySlug: "bottle-openers",
    title: "Leatherette-Handled Bottle Opener",
    shortDescription: "Stainless opener with leatherette grip — engravable handle.",
    description: "Stainless bottle opener with leatherette-wrapped handle. Engrave the leatherette panel with names or logos.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 6,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Rustic", "Wine", "Navy"] },
    heroPromptKey: "product:leatherette-opener",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PHOTO GIFTS — broaden the catalog
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "photo-slate",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Photo Slate",
    shortDescription: "Natural-edge slate panel — sublimated full-color photo.",
    description: "Natural-edge slate plaque with full-color sublimated photo. Includes display stand. Memorial, wedding, and gift favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["sublimation"],
    options: { Size: ["6×8", "8×10", "11×15"] },
    heroPromptKey: "product:photo-slate",
  },
  {
    slug: "metal-photo-panel",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Metal Photo Panel",
    shortDescription: "Aluminum photo panel — vibrant, scratch-resistant.",
    description: "Sublimated aluminum photo panel with white or pearl finish. Crisp colors, scratch- and fade-resistant.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["sublimation"],
    options: { Size: ["8×10", "11×14", "16×20", "20×30"], Finish: ["White Gloss", "Pearl"] },
    heroPromptKey: "product:metal-photo-panel",
  },
  {
    slug: "phone-case-custom",
    categorySlug: "photo-gifts",
    subcategorySlug: "phone-accessories",
    title: "Custom Phone Case",
    shortDescription: "Sublimated full-color phone case for current iPhone & Galaxy models.",
    description: "Slim-profile phone case with full-color sublimated print. Single-unit pricing for personalization or bulk for swag.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 6,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:phone-case-custom",
  },
  {
    slug: "pet-bandana",
    categorySlug: "photo-gifts",
    subcategorySlug: "pet-items",
    title: "Custom Pet Bandana",
    shortDescription: "Sublimated cotton bandana — pets, brand mascots, events.",
    description: "Soft cotton-poly bandana, sublimation printed full color. Perfect for adoption events, pet brands, or weddings with pets.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["sublimation"],
    options: { Size: ["Small", "Medium", "Large"] },
    heroPromptKey: "product:pet-bandana",
  },
  {
    slug: "pet-bowl-custom",
    categorySlug: "photo-gifts",
    subcategorySlug: "pet-items",
    title: "Custom Pet Bowl",
    shortDescription: "Stainless pet bowl with engraved name and photo accent.",
    description: "Stainless steel pet bowl with sublimated rim and engraved name. Personalize for groomers, vets, or gift shoppers.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving", "sublimation"],
    options: { Size: ["Small", "Medium", "Large"] },
    heroPromptKey: "product:pet-bowl",
  },
  {
    slug: "license-plate-custom",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Custom Front License Plate",
    shortDescription: "Aluminum front license plate — full-color sublimated.",
    description: "Standard 6×12 aluminum front license plate with full-color sublimated photo or graphic. Pre-drilled mounting holes.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:license-plate",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PERSONALIZED GIFTS — broaden the catalog
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "leatherette-portfolio",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leatherette Zippered Portfolio",
    shortDescription: "Premium zippered leatherette portfolio — cream engrave, refillable pad.",
    description: "Premium zippered portfolio in leatherette with refillable lined pad and pen loop. Engraves to a warm cream mark on multiple finishes.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 6,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Navy/Silver", "Wine/Gold"] },
    heroPromptKey: "product:leatherette-portfolio",
  },
  {
    slug: "leatherette-wallet",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leatherette Bifold Wallet",
    shortDescription: "Slim leatherette bifold — engraved monogram or initials.",
    description: "Slim bifold wallet with multiple card slots. Cream engrave on the inside flap or front face. Groomsman-favor and corporate-gift favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 6,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Rustic", "Navy", "Wine"] },
    heroPromptKey: "product:leatherette-wallet",
  },
  {
    slug: "money-clip-engraved",
    categorySlug: "personalized-gifts",
    subcategorySlug: "money-clips",
    title: "Engraved Stainless Money Clip",
    shortDescription: "Brushed stainless money clip — engraved monogram.",
    description: "Solid brushed-stainless money clip with engraved monogram or short message. Handsome groomsman gift or executive token.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:money-clip",
  },
  {
    slug: "pet-id-tag",
    categorySlug: "personalized-gifts",
    subcategorySlug: "pet-tags",
    title: "Stainless Pet ID Tag",
    shortDescription: "Engraved stainless pet tag — name, address, phone.",
    description: "Brushed-stainless pet ID tag with engraved name on one side and address/phone on the other. Includes split-ring.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: ["laser-engraving"],
    options: { Shape: ["Bone", "Round", "Heart", "Tag"] },
    heroPromptKey: "product:pet-id-tag",
  },
  {
    slug: "jewelry-stamping-service",
    categorySlug: "personalized-gifts",
    subcategorySlug: "jewelry-stamping",
    title: "Precious-Metal Stamping Service",
    shortDescription: "Bring your inventory — we laser-stamp gold, silver, platinum.",
    description: "Bring your jewelry inventory and we laser-stamp identification, hallmarks, weight, or custom marks on precious-metal pieces. Done in-house.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 3,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:jewelry-stamping",
    badges: ["Jeweler Favorite"],
  },
  {
    slug: "wood-photo-frame",
    categorySlug: "personalized-gifts",
    subcategorySlug: "frames",
    title: "Solid-Wood Photo Frame",
    shortDescription: "Walnut or maple frame — engraved presentation panel.",
    description: "Solid hardwood photo frame with engraved presentation panel below the photo opening. Holds standard 4×6 or 5×7 prints.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 6,
    decorationMethods: ["laser-engraving"],
    options: { Wood: ["Walnut", "Maple", "Oak"], Photo: ["4×6", "5×7", "8×10"] },
    heroPromptKey: "product:wood-photo-frame",
  },
  {
    slug: "ornament-engraved",
    categorySlug: "personalized-gifts",
    subcategorySlug: "ornaments",
    title: "Engraved Holiday Ornament",
    shortDescription: "Wood, slate, or acrylic ornament — name, year, photo.",
    description: "Holiday ornament in wood, slate, or acrylic. Personalize with names, dates, or photos for annual gifting programs.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving", "sublimation"],
    options: { Material: ["Wood", "Slate", "Acrylic"] },
    heroPromptKey: "product:engraved-ornament",
    badges: ["Seasonal"],
  },
  {
    slug: "acrylic-block-engraved",
    categorySlug: "personalized-gifts",
    subcategorySlug: "acrylic-pieces",
    title: "Engraved Acrylic Block",
    shortDescription: "Solid acrylic block — sub-surface laser engraving.",
    description: "Solid acrylic block with sub-surface laser engraving — looks like a small frozen-in moment. Common for milestones and anniversaries.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["3×3×1", "4×4×1", "5×5×1"] },
    heroPromptKey: "product:acrylic-block",
  },
  {
    slug: "engraved-cigar-set",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Cigar & Bar Gift Set",
    shortDescription: "Cigar holder + cutter + tray — leatherette case, engraved.",
    description: "Cigar holder, cutter, and ash tray in a leatherette presentation case. Engrave the case with names or a logo. Premium executive gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:cigar-bar-set",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // SPORTS & ACADEMIC AWARDS — broaden the catalog
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "resin-baseball-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Baseball Trophy",
    shortDescription: "Hand-painted resin batter — youth-league favorite.",
    description: "Detailed hand-painted resin batter on a weighted black base with engraving plate. Ships in five sizes for league budgets.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["6\"", "8\"", "10\"", "12\"", "14\""] },
    heroPromptKey: "product:resin-baseball",
  },
  {
    slug: "resin-basketball-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Basketball Trophy",
    shortDescription: "Hand-painted basketball figure — every-player or MVP.",
    description: "Resin basketball player figure on a weighted base, engraved plate. Cup, ball, and dribble variants available.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["6\"", "8\"", "10\"", "12\""] },
    heroPromptKey: "product:resin-basketball",
  },
  {
    slug: "resin-football-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Football Trophy",
    shortDescription: "Football figure on a weighted base — leagues, banquets, pop-warner.",
    description: "Detailed resin football figure with engraved plate. League-end favorite for ages 6-18.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["6\"", "8\"", "10\"", "12\""] },
    heroPromptKey: "product:resin-football",
  },
  {
    slug: "resin-cheer-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Cheer / Gymnastics Trophy",
    shortDescription: "Detailed cheer figure — competition-season favorite.",
    description: "Resin cheer or gymnastics figure on a weighted base. Plate, sport, and color customization included.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["6\"", "8\"", "10\"", "12\""] },
    heroPromptKey: "product:resin-cheer",
  },
  {
    slug: "metal-cup-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "cup-trophies",
    title: "Metal Cup Trophy",
    shortDescription: "Polished metal cup on tiered base — championship presentation.",
    description: "Brass-finished metal cup on a tiered walnut base with engraved presentation plate. Hand-presentation championship feel.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 11,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["12\"", "16\"", "20\"", "24\""] },
    heroPromptKey: "product:metal-cup-trophy",
  },
  {
    slug: "plastic-cup-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "cup-trophies",
    title: "Plastic Cup Trophy",
    shortDescription: "Lightweight plastic cup — youth budget-friendly.",
    description: "Lightweight gold-finish plastic cup on a black base with engraved plate. Affordable for large youth-league orders.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 6,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["8\"", "10\"", "12\""] },
    heroPromptKey: "product:plastic-cup-trophy",
  },
  {
    slug: "insert-holder-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "custom-insert-medals",
    title: "Custom-Insert Holder Medal",
    shortDescription: "Die-cast medal with swappable 2-inch full-color insert.",
    description: "Die-cast medal frame with full-color custom insert in the center. Swap inserts for sport, place, or year. Includes ribbon.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 8,
    decorationMethods: ["digital-insert", "laser-engraving"],
    options: { Color: ["Gold", "Silver", "Bronze", "Antique"] },
    heroPromptKey: "product:insert-holder-medal",
  },
  {
    slug: "place-medal-set",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "medals",
    title: "Gold/Silver/Bronze Place Medal Set",
    shortDescription: "Standard place-medal set for tournament podiums.",
    description: "Three-medal set in gold/silver/bronze, each with a 1st/2nd/3rd insert and a neck ribbon. Tournament and meet staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:place-medal-set",
  },
  {
    slug: "victory-torch-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "medals",
    title: "Victory Torch Medal",
    shortDescription: "Classic torch medal — 2-inch, ribbon included.",
    description: "Traditional victory-torch design die-cast medal, 2-inch, with school-color ribbon. Affordable bulk for season-end.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:victory-torch-medal",
  },
  {
    slug: "championship-ring",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "championship-rings",
    title: "Championship Ring",
    shortDescription: "Custom championship ring — team logo, year, name engraved.",
    description: "Custom-cast championship ring with team logo on top, year and name engraved on the side panels. League-finals favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 6,
    leadTimeDays: 30,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:championship-ring",
    badges: ["Premium"],
  },
  {
    slug: "chenille-letter-pin",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "chenille-pins",
    title: "Chenille Letter Pin",
    shortDescription: "Classic letterman pin — sports & academic recognition.",
    description: "Embroidered chenille letter pin in school colors. Wear on lettermen jackets or display in shadowboxes.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 12,
    decorationMethods: ["embroidery"],
    heroPromptKey: "product:chenille-letter-pin",
  },
  {
    slug: "satin-award-ribbon",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "ribbons",
    title: "Satin Award Ribbon",
    shortDescription: "Foil-stamped satin award ribbon — quick-turn.",
    description: "Standard satin award ribbon with foil-stamped customization. 1st through participant variants. Bulk-priced.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 5,
    decorationMethods: ["digital-print"],
    options: { Color: ["Blue 1st", "Red 2nd", "White 3rd", "Yellow 4th", "Green 5th", "Pink 6th"] },
    heroPromptKey: "product:satin-ribbon",
  },
  {
    slug: "stainless-dog-tag",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "dog-tags",
    title: "Stainless Sport Dog Tag",
    shortDescription: "Stainless dog-tag necklace — engraved sport, year, school.",
    description: "Engraved stainless dog tag on a beaded chain. Bulk-friendly award option for team rosters.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:stainless-dog-tag",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // BULK BLANKS — the new "buy what we print on" category
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "blank-cotton-tees-case",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-apparel",
    title: "Blank Cotton Tees — Case (72 ct)",
    shortDescription: "72 unisex 100% cotton tees — case-priced, your size run.",
    description: "Case of 72 unisex cotton tees in your specified size run. Case discount vs. dozen pricing. Mix sizes within the case.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: [],
    options: { Color: ["White", "Black", "Heather Grey", "Navy", "Red", "Forest", "Sand"] },
    heroPromptKey: "product:blank-cotton-tees-case",
    badges: ["Bulk Blank"],
  },
  {
    slug: "blank-fleece-hoodies-case",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-apparel",
    title: "Blank Fleece Hoodies — Case (24 ct)",
    shortDescription: "24 mid-weight pullover hoodies — case-priced.",
    description: "Case of 24 mid-weight pullover hoodies, mix sizes. Case discount vs. dozen pricing. Ships shrink-wrapped on a pallet for big orders.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: [],
    options: { Color: ["Black", "Navy", "Sport Grey", "Maroon", "Forest", "Safety Orange"] },
    heroPromptKey: "product:blank-hoodies-case",
    badges: ["Bulk Blank"],
  },
  {
    slug: "blank-polos-dozen",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-apparel",
    title: "Blank Pique Polos — Dozen",
    shortDescription: "12 cotton-poly pique polos — by-the-dozen pricing.",
    description: "Dozen of cotton-poly pique polos in solid colors. Mix-and-match size run within the dozen.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: [],
    options: { Color: ["White", "Black", "Navy", "Royal", "Hunter", "Burgundy"] },
    heroPromptKey: "product:blank-polos-dozen",
  },
  {
    slug: "blank-trucker-caps-dozen",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-apparel",
    title: "Blank Trucker Caps — Dozen",
    shortDescription: "12 structured snapback truckers — your colorway.",
    description: "Dozen of structured-front snapback trucker caps with mesh back. Mix solid or two-tone colorways.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: [],
    options: { Color: ["Black/Black", "Charcoal/Black", "Navy/White", "Red/White", "Heather Grey/Black"] },
    heroPromptKey: "product:blank-truckers-dozen",
  },
  {
    slug: "blank-polar-camel-tumblers-case",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-drinkware",
    title: "Blank Polar Camel Tumblers — Case (24 ct)",
    shortDescription: "Case of 24 powder-coated 20oz tumblers — single colorway.",
    description: "Case of 24 powder-coated 20oz vacuum tumblers. Single colorway per case for inventory simplicity. Engrave later or resell as-is.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: [],
    options: { Color: ["Black", "White", "Stainless", "Navy", "Red", "Sage"] },
    heroPromptKey: "product:blank-polar-camel-case",
  },
  {
    slug: "blank-ceramic-mugs-case",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-drinkware",
    title: "Blank White Ceramic Mugs — Case (36 ct)",
    shortDescription: "36 sublimation-ready 11oz white mugs.",
    description: "Case of 36 white ceramic 11oz mugs, sublimation-ready coating. Bulk-resale or in-house decoration.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: [],
    heroPromptKey: "product:blank-ceramic-mugs-case",
  },
  {
    slug: "blank-canvas-totes-dozen",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-bags-totes",
    title: "Blank Canvas Totes — Dozen",
    shortDescription: "12 natural-canvas totes — dozen pricing for bulk distribution.",
    description: "Dozen heavy 12oz natural-canvas totes with shoulder straps. Stage for printing or hand out as-is for events.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: [],
    options: { Color: ["Natural", "Black", "Navy"] },
    heroPromptKey: "product:blank-canvas-totes-dozen",
  },
  {
    slug: "blank-vinyl-roll-15in",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-vinyl-transfers",
    title: "Heat-Transfer Vinyl Roll (15\" × 5yd)",
    shortDescription: "PU heat-transfer vinyl roll — 15\" wide × 5 yards.",
    description: "Premium PU heat-transfer vinyl roll, 15-inch width, 5-yard length. For garment decoration with a household or industrial heat press.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 3,
    decorationMethods: [],
    options: { Color: ["Black", "White", "Red", "Royal", "Gold", "Silver", "Navy", "Forest"] },
    heroPromptKey: "product:htv-roll-15in",
  },
  {
    slug: "blank-dtf-film-roll",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-vinyl-transfers",
    title: "DTF Transfer Film Roll (24\" × 100m)",
    shortDescription: "Cold-peel DTF film — 24\" wide × 100 meters.",
    description: "Cold-peel direct-to-film transfer film roll. 24-inch width, 100 meter length. Pair with adhesive powder for in-house DTF.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: [],
    heroPromptKey: "product:dtf-film-roll",
  },
  {
    slug: "blank-sublimation-paper",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-vinyl-transfers",
    title: "Sublimation Paper (8.5×11, 100ct)",
    shortDescription: "Tacky-back sublimation paper — pack of 100 sheets.",
    description: "Tacky-back high-release sublimation paper, 8.5×11 sheets, 100 per pack. Great consistent transfer to polyester and coated blanks.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 3,
    decorationMethods: [],
    heroPromptKey: "product:sublimation-paper",
  },
  {
    slug: "blank-cardstock-cover-100lb",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-paper-stock",
    title: "Blank 100lb Cover Cardstock",
    shortDescription: "Sheet packs of 100lb cover — matte, gloss, or uncoated.",
    description: "100lb cover cardstock in 8.5×11, 11×17, or 12×18 sheets. Ships 250 or 500 per pack. Choose matte, gloss, or uncoated finish.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 3,
    decorationMethods: [],
    options: { Size: ["8.5×11", "11×17", "12×18"], Finish: ["Matte", "Gloss", "Uncoated"] },
    heroPromptKey: "product:blank-cardstock-100lb",
  },
  {
    slug: "blank-label-sheets",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-paper-stock",
    title: "Blank Label Sheets",
    shortDescription: "Adhesive label sheets — full sheet or die-cut.",
    description: "Blank pressure-sensitive label sheets in full-page or pre-cut die formats. Run through your laser or inkjet printer.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 3,
    decorationMethods: [],
    options: { Format: ["Full sheet", "10-up", "30-up", "Address (60-up)"] },
    heroPromptKey: "product:blank-label-sheets",
  },
  {
    slug: "blank-leatherette-sheet",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-awards-plaques",
    title: "Blank Leatherette Engraving Sheet",
    shortDescription: "12×24 leatherette sheets — engrave-ready.",
    description: "Engrave-ready 12×24 leatherette sheets in multiple two-tone colors. Cut, score, and engrave with any laser system.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 3,
    decorationMethods: [],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Navy/Silver", "Wine/Gold", "Gray/Black"] },
    heroPromptKey: "product:blank-leatherette-sheet",
  },
  {
    slug: "blank-wood-plaque-base",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-awards-plaques",
    title: "Blank Wood Plaque Base",
    shortDescription: "Walnut or rosewood plaque blanks — engrave or apply your own plate.",
    description: "Pre-finished walnut or rosewood plaque blanks ready for engraving or your own metal/leatherette presentation plate.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: [],
    options: { Wood: ["Walnut", "Rosewood"], Size: ["7×9", "8×10", "9×12"] },
    heroPromptKey: "product:blank-plaque-base",
  },
  {
    slug: "blank-acrylic-trophy-blank",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-awards-plaques",
    title: "Blank Acrylic Trophy Block",
    shortDescription: "Solid acrylic blocks — engraving-ready trophy blanks.",
    description: "Solid clear-acrylic blocks in jewel or rectangular cuts. Pre-cut and polished, engrave to spec or UV-print on the front face.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: [],
    options: { Shape: ["Rectangular", "Jewel", "Diamond"], Size: ["5\"", "7\"", "9\""] },
    heroPromptKey: "product:blank-acrylic-block",
  },
];
