import type { SampleProduct } from "./sample-products";

/**
 * Catalog expansion batch 3 — gap-filling from gapromotional.com's wider
 * catalog (eco-friendly, health/PPE, camping/outdoor, tech accessories,
 * writing tools, stationery, office organization, women's/kids' apparel
 * deeper variants) and additional photo-gift / personalized-gift coverage.
 *
 * All priced as `quote`. Brand names stay genericized.
 */
export const importedProductsBatch3: SampleProduct[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // ECO-FRIENDLY / SUSTAINABLE
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "recycled-cotton-tote",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bags",
    title: "Recycled Cotton Tote",
    shortDescription: "100% recycled-cotton tote — eco-event giveaway.",
    description: "Heavy 12oz tote made from 100% recycled cotton. Earth-tone natural color, prints crisp via screen or DTF.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 6,
    decorationMethods: ["screen-print", "heat-transfer"],
    options: { Color: ["Natural", "Charcoal Recycled"] },
    heroPromptKey: "product:recycled-cotton-tote",
    badges: ["Eco-Friendly"],
  },
  {
    slug: "bamboo-pen",
    categorySlug: "custom-printing",
    subcategorySlug: "address-labels",
    title: "Bamboo Eco Pen",
    shortDescription: "Bamboo-barrel pen — sustainable promo pen alternative.",
    description: "Click-action pen with bamboo barrel and recycled-plastic clip. Laser engraves clean. Eco-conference favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:bamboo-pen",
    badges: ["Eco-Friendly"],
  },
  {
    slug: "wheat-straw-notebook",
    categorySlug: "custom-printing",
    subcategorySlug: "note-pads",
    title: "Wheat-Straw Notebook",
    shortDescription: "Wheat-straw composite cover notebook — sustainable swag.",
    description: "Pocket notebook with wheat-straw composite cover and recycled paper. Imprinted logo. Eco-mindful corporate gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 10,
    decorationMethods: ["uv-print"],
    heroPromptKey: "product:wheat-straw-notebook",
    badges: ["Eco-Friendly"],
  },
  {
    slug: "reusable-bamboo-utensil-set",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Bamboo Travel Utensil Set",
    shortDescription: "Fork/knife/spoon/chopsticks in a leatherette pouch.",
    description: "Travel-ready bamboo utensil set with cleaning brush in a leatherette zipper pouch. Engrave the pouch.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:bamboo-utensil-set",
    badges: ["Eco-Friendly"],
  },
  {
    slug: "metal-straws-set",
    categorySlug: "drinkware",
    subcategorySlug: "tumblers",
    title: "Stainless Straw Set",
    shortDescription: "Set of 4 stainless straws + cleaning brush in pouch.",
    description: "Four reusable stainless steel straws with cleaning brush, in a fabric pouch. Sustainable alternative to plastic straws.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:metal-straws-set",
    badges: ["Eco-Friendly"],
  },
  {
    slug: "rpet-backpack",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bags",
    title: "Recycled (rPET) Backpack",
    shortDescription: "Backpack made from recycled plastic bottles.",
    description: "Daily commuter backpack made from recycled PET bottles. Padded laptop sleeve, water-bottle pockets. Sustainable corporate gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 11,
    decorationMethods: ["embroidery", "heat-transfer"],
    options: { Color: ["Black", "Charcoal", "Navy"] },
    heroPromptKey: "product:rpet-backpack",
    badges: ["Eco-Friendly"],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // HEALTH / PPE / FIRST AID
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "hand-sanitizer-bottle",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Hand Sanitizer Bottle",
    shortDescription: "1oz hand sanitizer with imprinted label.",
    description: "Pocket-size 1oz hand sanitizer with custom-printed full-color label. Health-event and clinic giveaway.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 9,
    decorationMethods: ["digital-print"],
    heroPromptKey: "product:hand-sanitizer-bottle",
  },
  {
    slug: "first-aid-kit-mini",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Mini First Aid Kit",
    shortDescription: "Pocket first-aid kit — branded zippered case.",
    description: "Compact first-aid kit with bandages, alcohol wipes, and tape in a zippered case. Imprint logo on the case.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 10,
    decorationMethods: ["heat-transfer"],
    heroPromptKey: "product:first-aid-kit-mini",
  },
  {
    slug: "lip-balm-promo",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Imprinted Lip Balm",
    shortDescription: "SPF 15 lip balm — full-color label.",
    description: "Standard lip-balm tube with SPF 15 and full-color custom label. Trade-show, swag-bag, wedding-favor staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 9,
    decorationMethods: ["digital-print"],
    options: { Flavor: ["Mint", "Vanilla", "Strawberry", "Unflavored"] },
    heroPromptKey: "product:lip-balm-promo",
  },
  {
    slug: "sunscreen-tube",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "SPF 30 Sunscreen Tube",
    shortDescription: "1oz SPF 30 sunscreen — branded label.",
    description: "1oz SPF 30 sunscreen tube with custom-printed label. Outdoor-event and golf-tournament favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 10,
    decorationMethods: ["digital-print"],
    heroPromptKey: "product:sunscreen-tube",
  },
  {
    slug: "fabric-face-mask",
    categorySlug: "apparel-headwear",
    subcategorySlug: "personal-protection",
    title: "Reusable Fabric Face Mask",
    shortDescription: "3-layer cotton/poly mask — sublimated full-color.",
    description: "Reusable 3-layer fabric face mask with adjustable ear loops. Sublimation full-color print on the front panel.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 8,
    decorationMethods: ["sublimation"],
    options: { Color: ["Black", "White", "Navy", "Custom Print"] },
    heroPromptKey: "product:fabric-face-mask",
  },
  {
    slug: "work-gloves",
    categorySlug: "apparel-headwear",
    subcategorySlug: "personal-protection",
    title: "Work Gloves",
    shortDescription: "Synthetic-leather work gloves — light construction.",
    description: "Synthetic-leather work gloves with reinforced palm. Embroidered cuff for company logo.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["embroidery"],
    options: { Size: ["S", "M", "L", "XL"] },
    heroPromptKey: "product:work-gloves",
  },
  {
    slug: "hard-hat",
    categorySlug: "apparel-headwear",
    subcategorySlug: "personal-protection",
    title: "ANSI Hard Hat",
    shortDescription: "Type 1 Class E ANSI hard hat — UV-printed logo.",
    description: "ANSI-rated Type 1 Class E hard hat with 4-point ratchet suspension. UV-printed logo on the front. Construction-team standard.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["uv-print"],
    options: { Color: ["White", "Yellow", "Hi-Vis Orange", "Hi-Vis Lime", "Blue", "Red"] },
    heroPromptKey: "product:hard-hat",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CAMPING / OUTDOOR
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "camp-chair-folding",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Folding Camp Chair",
    shortDescription: "Standard folding camp chair with carry bag.",
    description: "Folding camp chair with armrests, cup holder, and carry bag. Imprint logo on the carry bag or back panel.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 14,
    decorationMethods: ["heat-transfer", "screen-print"],
    options: { Color: ["Black", "Navy", "Royal", "Red", "Hunter"] },
    heroPromptKey: "product:camp-chair-folding",
  },
  {
    slug: "stadium-blanket",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Stadium Blanket",
    shortDescription: "Sherpa-lined stadium blanket — game-day favorite.",
    description: "Sherpa-lined stadium blanket with carry strap. Embroidered or screen-printed logo. Football tailgate and outdoor-event staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 11,
    decorationMethods: ["embroidery", "screen-print"],
    options: { Color: ["Charcoal", "Navy", "Hunter", "Maroon"] },
    heroPromptKey: "product:stadium-blanket",
  },
  {
    slug: "beach-towel-printed",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Sublimated Beach Towel",
    shortDescription: "30×60 beach towel — full-color sublimation print.",
    description: "Polyester-blend beach towel, 30×60, with full-color edge-to-edge sublimation. Resort and event giveaway.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 11,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:beach-towel-printed",
  },
  {
    slug: "outdoor-umbrella",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Auto-Open Folding Umbrella",
    shortDescription: "Compact auto-open umbrella — solid imprint.",
    description: "Compact auto-open/close folding umbrella with carrying sleeve. Imprinted logo on one panel.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["heat-transfer"],
    options: { Color: ["Black", "Navy", "Royal", "Red"] },
    heroPromptKey: "product:outdoor-umbrella",
  },
  {
    slug: "soft-cooler-tote",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bags",
    title: "Soft-Sided Cooler Tote",
    shortDescription: "Insulated soft cooler — picnic and tailgate.",
    description: "Insulated soft-sided cooler tote, holds ~24 cans + ice. Embroidered or heat-transferred logo. Outdoor-event favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 10,
    decorationMethods: ["embroidery", "heat-transfer"],
    options: { Color: ["Black", "Navy", "Charcoal"] },
    heroPromptKey: "product:soft-cooler-tote",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // TECH / OFFICE ACCESSORIES
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "earbuds-bluetooth",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Bluetooth Earbuds Set",
    shortDescription: "Wireless earbuds with charging case — engraved.",
    description: "Wireless Bluetooth earbuds in a leatherette-finished charging case. Engrave the case lid with company logo or initials.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 14,
    decorationMethods: ["laser-engraving"],
    options: { Case: ["Black/Silver", "Rustic/Gold"] },
    heroPromptKey: "product:earbuds-bluetooth",
    badges: ["Premium"],
  },
  {
    slug: "webcam-cover",
    categorySlug: "photo-gifts",
    subcategorySlug: "phone-accessories",
    title: "Sliding Webcam Cover",
    shortDescription: "Slim sliding webcam cover — privacy giveaway.",
    description: "Ultra-thin sliding webcam cover. Sticks to laptops and tablets. Imprint full-color logo. Conference / IT-team favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 9,
    decorationMethods: ["uv-print"],
    options: { Color: ["Black", "White"] },
    heroPromptKey: "product:webcam-cover",
  },
  {
    slug: "laptop-sleeve-printed",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bags",
    title: "Custom Laptop Sleeve",
    shortDescription: "13/15/16 inch laptop sleeve — full-color sublimated.",
    description: "Neoprene laptop sleeve with full-color sublimation. Available in standard laptop sizes. Single-unit personalization.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["sublimation"],
    options: { Size: ["13\"", "15\"", "16\""] },
    heroPromptKey: "product:laptop-sleeve-printed",
  },
  {
    slug: "blue-light-glasses",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Blue-Light Glasses with Case",
    shortDescription: "Computer glasses + leatherette case — engraved case.",
    description: "Blue-light filtering computer glasses in a hard leatherette case. Engrave the case with company logo.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 11,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:blue-light-glasses",
  },
  {
    slug: "phone-popgrip-leatherette",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leatherette Phone Pop-Grip",
    shortDescription: "Pop-out phone grip with leatherette panel — engraved.",
    description: "Pop-out phone grip with engravable leatherette top panel. Cream engrave on multiple finishes.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Wine/Gold"] },
    heroPromptKey: "product:phone-popgrip-leatherette",
  },
  {
    slug: "wireless-mouse",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Wireless Mouse",
    shortDescription: "Bluetooth wireless mouse — UV-printed top panel.",
    description: "Slim Bluetooth wireless mouse with rechargeable battery. UV-printed full-color logo on the top panel.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 12,
    decorationMethods: ["uv-print"],
    options: { Color: ["Black", "White", "Silver"] },
    heroPromptKey: "product:wireless-mouse",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // WRITING TOOLS BEYOND PENS
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "branded-pencil",
    categorySlug: "custom-printing",
    subcategorySlug: "address-labels",
    title: "Imprinted #2 Pencil",
    shortDescription: "Standard #2 pencils — bulk-printed for schools.",
    description: "Pre-sharpened #2 pencils with imprinted logo or text. Available in many barrel colors. School-supply staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 7,
    decorationMethods: ["uv-print"],
    options: { Color: ["Yellow Classic", "Black", "Navy", "Royal", "Red", "Forest"] },
    heroPromptKey: "product:branded-pencil",
  },
  {
    slug: "highlighter-printed",
    categorySlug: "custom-printing",
    subcategorySlug: "address-labels",
    title: "Imprinted Highlighter",
    shortDescription: "Standard chisel-tip highlighter — single-color logo.",
    description: "Standard chisel-tip highlighter in five colors with single-color logo imprint. Office and school giveaway.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 7,
    decorationMethods: ["uv-print"],
    options: { Color: ["Yellow", "Pink", "Green", "Orange", "Blue"] },
    heroPromptKey: "product:highlighter-printed",
  },
  {
    slug: "permanent-marker-printed",
    categorySlug: "custom-printing",
    subcategorySlug: "address-labels",
    title: "Imprinted Permanent Marker",
    shortDescription: "Industrial permanent marker — single-color barrel imprint.",
    description: "Industrial permanent marker (fine or chisel tip) with imprinted logo on the barrel. Office, warehouse, classroom.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 7,
    decorationMethods: ["uv-print"],
    options: { Tip: ["Fine", "Chisel"], Color: ["Black", "Blue", "Red"] },
    heroPromptKey: "product:permanent-marker-printed",
  },
  {
    slug: "writing-gift-set",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Pen + Pencil Gift Set",
    shortDescription: "Matched pen + pencil in engraved leatherette case.",
    description: "Matched twist-action pen and mechanical pencil pair in a leatherette gift case. Engrave the case for an executive gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving"],
    options: { Case: ["Black/Silver", "Rustic/Gold", "Wine/Gold"] },
    heroPromptKey: "product:writing-gift-set",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // STATIONERY EXPANSION
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "letterhead",
    categorySlug: "custom-printing",
    subcategorySlug: "flyers",
    title: "Custom Letterhead",
    shortDescription: "70lb premium letterhead — full-color or two-color.",
    description: "Full-color letterhead on 70lb premium offset paper. Standard 8.5×11 with bleeds. Includes envelopes if requested.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 7,
    decorationMethods: ["offset-print"],
    options: { Quantity: ["250", "500", "1000", "2500"] },
    heroPromptKey: "product:letterhead",
  },
  {
    slug: "envelope-printed",
    categorySlug: "custom-printing",
    subcategorySlug: "address-labels",
    title: "Custom Printed Envelope",
    shortDescription: "#10 business envelopes — printed return address.",
    description: "Standard #10 business envelopes (or A6/A7 invitation sizes) printed with return address and optional full-color graphic.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 7,
    decorationMethods: ["offset-print"],
    options: { Size: ["#10", "A6", "A7", "9×12"] },
    heroPromptKey: "product:envelope-printed",
  },
  {
    slug: "business-calendar-wall",
    categorySlug: "custom-printing",
    subcategorySlug: "magnet-calendars",
    title: "Custom Wall Calendar",
    shortDescription: "12-month wall calendar — custom photos and dates.",
    description: "12-month wall calendar with custom photos, dates, and brand logo. Spiral-bound with hanging hook.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 12,
    decorationMethods: ["digital-print"],
    options: { Size: ["8.5×11", "11×17"] },
    heroPromptKey: "product:wall-calendar",
  },
  {
    slug: "desk-calendar",
    categorySlug: "custom-printing",
    subcategorySlug: "magnet-calendars",
    title: "Custom Desk Calendar",
    shortDescription: "Easel-back desk calendar — month-per-page.",
    description: "Spiral-bound easel-back desk calendar with custom photos. Month-per-page format.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 11,
    decorationMethods: ["digital-print"],
    heroPromptKey: "product:desk-calendar",
  },
  {
    slug: "appointment-cards",
    categorySlug: "custom-printing",
    subcategorySlug: "business-cards",
    title: "Appointment Cards",
    shortDescription: "Standard 3.5×2 business-card-sized appointment slips.",
    description: "Business-card-sized appointment cards with fields for date, time, and notes. Doctor, dentist, salon staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 5,
    decorationMethods: ["offset-print"],
    heroPromptKey: "product:appointment-cards",
  },
  {
    slug: "tickets-numbered",
    categorySlug: "custom-printing",
    subcategorySlug: "address-labels",
    title: "Numbered Event Tickets",
    shortDescription: "Sequentially numbered raffle / event tickets.",
    description: "Standard 2×6 raffle or event tickets with sequential numbering and detachable stub. Bulk-priced for fundraisers.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 500,
    leadTimeDays: 7,
    decorationMethods: ["offset-print"],
    heroPromptKey: "product:tickets-numbered",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // OFFICE ORGANIZATION
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "binder-printed",
    categorySlug: "custom-printing",
    subcategorySlug: "brochures",
    title: "Custom 3-Ring Binder",
    shortDescription: "Vinyl-clad 3-ring binder with custom-printed cover.",
    description: "Standard 1\", 1.5\", or 2\" 3-ring binder with full-color custom-printed cover and spine. Sales-kit and training-manual staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 11,
    decorationMethods: ["digital-print"],
    options: { Size: ["1\"", "1.5\"", "2\"", "3\""] },
    heroPromptKey: "product:binder-printed",
  },
  {
    slug: "clipboard-printed",
    categorySlug: "custom-printing",
    subcategorySlug: "brochures",
    title: "Custom Clipboard",
    shortDescription: "Hardboard clipboard with full-color sublimated face.",
    description: "Standard hardboard clipboard with full-color sublimated face. Real-estate, restaurant, contractor, clinic.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 8,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:clipboard-printed",
  },
  {
    slug: "memo-board-magnetic",
    categorySlug: "personalized-gifts",
    subcategorySlug: "frames",
    title: "Magnetic Memo Board",
    shortDescription: "Engraved magnetic memo board for kitchen or office.",
    description: "Magnetic memo board with engraved family name or company logo. Includes magnets and dry-erase marker.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["12×16", "16×20"] },
    heroPromptKey: "product:memo-board-magnetic",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // APPAREL / WOMEN'S / KIDS DEEPER
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "womens-dress-tee",
    categorySlug: "apparel-headwear",
    subcategorySlug: "womens",
    title: "Women's Dress Tee",
    shortDescription: "Tailored woven tee — boutique apparel.",
    description: "Tailored woven cotton/poly tee with feminine cut. Embroiders cleanly at chest and sleeve.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["embroidery"],
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL"], Color: ["White", "Black", "French Blue", "Light Pink"] },
    heroPromptKey: "product:womens-dress-tee",
  },
  {
    slug: "womens-tank",
    categorySlug: "apparel-headwear",
    subcategorySlug: "womens",
    title: "Women's Racerback Tank",
    shortDescription: "Lightweight racerback tank — gym & yoga.",
    description: "Lightweight tri-blend racerback tank. DTF / sublimation prints great on the chest panel.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["dtf", "sublimation"],
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL"], Color: ["Heather Grey", "Black", "White", "Pink", "Mint"] },
    heroPromptKey: "product:womens-tank",
  },
  {
    slug: "womens-leggings",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bottoms",
    title: "Women's Performance Leggings",
    shortDescription: "Full-length performance leggings — sublimated panel.",
    description: "Mid-rise performance leggings with hip pockets. Sublimated logo on the side hip panel.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 11,
    decorationMethods: ["sublimation"],
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL"], Color: ["Black", "Charcoal", "Navy"] },
    heroPromptKey: "product:womens-leggings",
  },
  {
    slug: "youth-jersey",
    categorySlug: "apparel-headwear",
    subcategorySlug: "youth",
    title: "Youth Sport Jersey",
    shortDescription: "Sublimated youth jersey — team-name & number.",
    description: "Full-sublimation youth sport jersey with custom team name, player name, and number. Soccer, basketball, baseball cuts.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 14,
    decorationMethods: ["sublimation"],
    options: { Cut: ["Soccer", "Basketball", "Baseball"] },
    heroPromptKey: "product:youth-jersey",
  },
  {
    slug: "kids-bib-sublimated",
    categorySlug: "apparel-headwear",
    subcategorySlug: "youth",
    title: "Sublimated Kids' Bib",
    shortDescription: "Soft fabric bib with full-color sublimated face.",
    description: "Soft polyester-blend bib with snap closure and full-color sublimation. Baby-shower and gift-shop staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:kids-bib-sublimated",
  },
  {
    slug: "athletic-shorts-women",
    categorySlug: "apparel-headwear",
    subcategorySlug: "womens",
    title: "Women's Athletic Shorts",
    shortDescription: "Performance shorts cut for women — team and gym.",
    description: "Polyester athletic shorts cut for women with elastic waist and side pockets. Decorate side leg with team mark.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 8,
    decorationMethods: ["screen-print", "embroidery", "heat-transfer"],
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL"], Color: ["Black", "Navy", "Royal", "Red"] },
    heroPromptKey: "product:athletic-shorts-women",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PHOTO GIFTS — additional novelty
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "photo-canvas-print",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Photo Canvas Wall Print",
    shortDescription: "Wrapped canvas wall print — gallery quality.",
    description: "Gallery-wrapped canvas with full-color sublimated photo. Multiple sizes from 8×10 to 24×36. Hanging hardware included.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["sublimation"],
    options: { Size: ["8×10", "11×14", "16×20", "24×36"] },
    heroPromptKey: "product:photo-canvas-print",
  },
  {
    slug: "photo-mug-collage",
    categorySlug: "photo-gifts",
    subcategorySlug: "phone-accessories",
    title: "Photo Collage Mug",
    shortDescription: "11oz mug — multi-photo collage wrap design.",
    description: "11oz ceramic mug sublimated with a full-color multi-photo collage wrap. Birthday and family-gift favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:photo-mug-collage",
  },
  {
    slug: "ornament-photo",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Photo Ornament",
    shortDescription: "Aluminum or wood ornament with sublimated photo.",
    description: "2-sided aluminum or wood ornament with full-color photo print. Holiday and memorial gift staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["sublimation"],
    options: { Material: ["Aluminum", "Wood", "Acrylic"] },
    heroPromptKey: "product:ornament-photo",
  },
  {
    slug: "playing-cards-photo",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Custom Photo Playing Cards",
    shortDescription: "Standard deck of playing cards — custom back design.",
    description: "Standard 52-card deck with custom photo or graphic back design and tuck box. Wedding and corporate-event favor.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 12,
    decorationMethods: ["offset-print"],
    heroPromptKey: "product:playing-cards-photo",
  },
  {
    slug: "photo-mousepad-collage",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Photo Collage Mouse Pad",
    shortDescription: "Mouse pad with multi-photo sublimated collage.",
    description: "Standard 7.5×9 mouse pad with full-color multi-photo collage. Personalized employee or family gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:photo-mousepad-collage",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CORPORATE AWARDS — more variants
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "crystal-globe-award",
    categorySlug: "corporate-awards",
    subcategorySlug: "crystal-awards",
    title: "Crystal Globe Award",
    shortDescription: "Optical crystal globe on a black base — global achievement.",
    description: "Optical crystal globe mounted on a polished black base. Engraved presentation plate. International / global-leadership award.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 11,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["3.5\"", "4.5\"", "5\""] },
    heroPromptKey: "product:crystal-globe-award",
  },
  {
    slug: "crystal-cube-award",
    categorySlug: "corporate-awards",
    subcategorySlug: "crystal-awards",
    title: "Sub-Surface Crystal Cube",
    shortDescription: "3D laser-engraved crystal cube — sub-surface depth.",
    description: "Solid optical crystal cube with 3D sub-surface laser engraving. Looks like a tiny holographic moment frozen in glass.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 12,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["2×2×2", "3×3×3", "4×4×4"] },
    heroPromptKey: "product:crystal-cube-award",
    badges: ["Premium"],
  },
  {
    slug: "diamond-glass-award",
    categorySlug: "corporate-awards",
    subcategorySlug: "glass-awards",
    title: "Diamond Glass Award",
    shortDescription: "Diamond-cut glass on a black base — modern recognition.",
    description: "Diamond-cut tinted glass mounted on a polished black base. Modern, geometric recognition piece.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["sand-etch", "laser-engraving"],
    options: { Size: ["6\"", "8\"", "10\""] },
    heroPromptKey: "product:diamond-glass-award",
  },
  {
    slug: "chrome-pen-set-engraved",
    categorySlug: "corporate-awards",
    subcategorySlug: "desk-pieces",
    title: "Chrome Pen Set on Marble Base",
    shortDescription: "Two-pen desk set on a marble base — engraved.",
    description: "Two chrome pens mounted on a marble base with engraved presentation plate. Executive-desk staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { "Marble color": ["Black", "Green", "Burgundy"] },
    heroPromptKey: "product:chrome-pen-set",
  },
  {
    slug: "letter-opener-engraved",
    categorySlug: "corporate-awards",
    subcategorySlug: "desk-pieces",
    title: "Engraved Letter Opener",
    shortDescription: "Stainless letter opener — engraved handle.",
    description: "Stainless letter opener with engraved handle. Presented in a leatherette gift box. Old-school executive gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:letter-opener-engraved",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PERSONALIZED GIFTS — more leatherette / wood variants
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "leatherette-coaster-square-set",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leatherette Square Coaster Set",
    shortDescription: "4-pack square leatherette coasters in a holder.",
    description: "Four square leatherette coasters in a matching holder. Engraves cream monogram or family name.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Wine/Gold", "Navy/Silver"] },
    heroPromptKey: "product:leatherette-coaster-square-set",
  },
  {
    slug: "leatherette-jewelry-box",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leatherette Jewelry Box",
    shortDescription: "Leatherette jewelry box with mirrored lid — engraved.",
    description: "Leatherette jewelry box with mirrored interior lid and felt-lined slots. Engraves cream monogram on the lid. Bridesmaid gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Wine/Gold"] },
    heroPromptKey: "product:leatherette-jewelry-box",
  },
  {
    slug: "leatherette-recipe-binder",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leatherette Recipe Binder",
    shortDescription: "Recipe binder with engraved leatherette cover.",
    description: "Recipe binder with refillable lined and tabbed pages, in a leatherette cover. Engraved family name on the cover. Wedding-shower favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Wine/Gold"] },
    heroPromptKey: "product:leatherette-recipe-binder",
  },
  {
    slug: "wood-keepsake-box",
    categorySlug: "personalized-gifts",
    subcategorySlug: "frames",
    title: "Wood Keepsake Box",
    shortDescription: "Walnut keepsake box with engraved lid — heirloom gift.",
    description: "Walnut keepsake box with hinged lid. Engrave names, dates, or a short message. Felt-lined interior. Heirloom-quality gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["Small", "Medium", "Large"] },
    heroPromptKey: "product:wood-keepsake-box",
  },
  {
    slug: "rocks-glass-engraved",
    categorySlug: "drinkware",
    subcategorySlug: "wine-sets",
    title: "Engraved Rocks Glass Set",
    shortDescription: "Heavy-base whiskey rocks glasses — set of 2 or 4.",
    description: "Heavy-base 11oz whiskey rocks glasses, sand-etched with monogram or short message. Bourbon-club gift staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["sand-etch"],
    options: { Set: ["Set of 2", "Set of 4", "Set of 6"] },
    heroPromptKey: "product:rocks-glass-engraved",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // BULK BLANKS — additional staples
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "blank-aprons-dozen",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-apparel",
    title: "Blank Bib Aprons — Dozen",
    shortDescription: "12 heavy twill bib aprons — dozen pricing.",
    description: "Dozen of heavy twill bib aprons in solid colors. Stage for in-house decoration or hand out to staff as-is.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: [],
    options: { Color: ["Black", "Charcoal", "Khaki", "White"] },
    heroPromptKey: "product:blank-aprons-dozen",
  },
  {
    slug: "blank-koozies-bulk",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-drinkware",
    title: "Blank Neoprene Koozies — Box (100 ct)",
    shortDescription: "Box of 100 blank neoprene can coolers — single colorway.",
    description: "Box of 100 blank neoprene can coolers (koozies) in a single solid colorway. Stage for screen-print or resell.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: [],
    options: { Color: ["Black", "Red", "Royal", "Navy", "Pink", "White"] },
    heroPromptKey: "product:blank-koozies-bulk",
  },
  {
    slug: "blank-sublimation-mugs-case",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-drinkware",
    title: "Blank Sublimation Mugs — Case (36 ct)",
    shortDescription: "36 white sublimation-coated 11oz mugs.",
    description: "Case of 36 white ceramic 11oz mugs with sublimation coating. Optimized for in-house dye-sub production runs.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: [],
    heroPromptKey: "product:blank-sublimation-mugs-case",
  },
  {
    slug: "blank-lanyards-bulk",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-bags-totes",
    title: "Blank Lanyards — Box (100 ct)",
    shortDescription: "Box of 100 blank polyester lanyards — solid color.",
    description: "Box of 100 blank polyester lanyards in solid colors with swivel clip. Stage for in-house sublimation imprint.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: [],
    options: { Color: ["Black", "Royal", "Red", "White", "Navy"] },
    heroPromptKey: "product:blank-lanyards-bulk",
  },
  {
    slug: "blank-medal-ribbons",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-awards-plaques",
    title: "Blank Neck Ribbons — Pack (100 ct)",
    priceStatus: "quote",
    basePriceCents: null,
    shortDescription: "100 blank neck ribbons — pair with medal blanks.",
    description: "Pack of 100 satin neck ribbons in standard colors. Pair with medal blanks for full-stock medal builds.",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: [],
    options: { Color: ["Red/White/Blue", "Solid Red", "Solid Blue", "Solid White", "Solid Black", "School-Color Custom"] },
    heroPromptKey: "product:blank-medal-ribbons",
  },
];
