import type { SampleProduct } from "./sample-products";

/**
 * Catalog expansion batch 2 — deeper coverage drawn from the same nine
 * competitor catalogs as imported-products.ts.
 *
 * Focus: drinkware variants (full Polar Camel + glassware line), sport-specific
 * resin trophies and medals (every major sport), promo/office items
 * (pens, lanyards, USB drives, stress balls, etc.), apparel deeper (women's,
 * youth, jerseys, scrubs variants), and more print-shop format coverage.
 *
 * Pricing uses `quote` status across the board.
 */
export const importedProductsBatch2: SampleProduct[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // DRINKWARE — fill out the Polar Camel line + glassware + ceramics
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "polar-camel-12oz-water-bottle",
    categorySlug: "drinkware",
    subcategorySlug: "water-bottles",
    title: "Polar Camel 12oz Sport Bottle",
    shortDescription: "Compact 12oz vacuum sport bottle — kids and small-grip.",
    description: "Slim 12oz vacuum-insulated water bottle with sport-cap. Engraves to a clean silver mark. Great for school events and kids' gifts.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving", "uv-print"],
    options: { Color: ["Stainless", "Black", "Sage", "Pink", "Teal"] },
    heroPromptKey: "product:polar-camel-12oz-water-bottle",
  },
  {
    slug: "polar-camel-20oz-water-bottle",
    categorySlug: "drinkware",
    subcategorySlug: "water-bottles",
    title: "Polar Camel 20oz Water Bottle",
    shortDescription: "Standard 20oz vacuum water bottle with screw cap.",
    description: "Workhorse 20oz vacuum water bottle. Fits cup holders. Engraves to a silver mark beneath the powder coat.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Stainless", "Black", "Navy", "Sage", "Rose Gold"] },
    heroPromptKey: "product:polar-camel-20oz-water-bottle",
  },
  {
    slug: "polar-camel-leatherette-tumbler",
    categorySlug: "drinkware",
    subcategorySlug: "tumblers",
    title: "Leatherette-Wrapped 20oz Tumbler",
    shortDescription: "20oz vacuum tumbler in leatherette sleeve — premium engrave.",
    description: "Stainless 20oz tumbler wrapped in leatherette for premium engraving — cream mark on the leatherette panel.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Wine/Gold", "Navy/Silver"] },
    heroPromptKey: "product:polar-camel-leatherette-tumbler",
  },
  {
    slug: "silicone-grip-tumbler-20oz",
    categorySlug: "drinkware",
    subcategorySlug: "tumblers",
    title: "Silicone-Grip 20oz Tumbler",
    shortDescription: "Anti-slip silicone-wrapped tumbler — outdoor and gym use.",
    description: "Stainless 20oz tumbler wrapped in textured silicone for grip. Engraves on the metal panel between silicone bands.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Navy", "Forest", "Stainless"] },
    heroPromptKey: "product:silicone-grip-tumbler-20oz",
  },
  {
    slug: "polar-camel-pilsner",
    categorySlug: "drinkware",
    subcategorySlug: "wine-sets",
    title: "Polar Camel Pilsner Glass",
    shortDescription: "Stainless pilsner glass — vacuum-insulated, engraves clean.",
    description: "Stainless steel pilsner glass with vacuum insulation. Engraves a silver crest beneath the powder coat. A wedding/groomsman favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Stainless", "Black", "Rose Gold"] },
    heroPromptKey: "product:polar-camel-pilsner",
  },
  {
    slug: "polar-camel-pint-glass",
    categorySlug: "drinkware",
    subcategorySlug: "wine-sets",
    title: "Polar Camel Stainless Pint Glass",
    shortDescription: "16oz stainless pint glass — bar-style with engrave.",
    description: "Bar-style 16oz stainless pint glass with vacuum insulation. Engrave for breweries, bars, beer-club gifts.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Stainless", "Black"] },
    heroPromptKey: "product:polar-camel-pint-glass",
  },
  {
    slug: "kids-sippy-cup",
    categorySlug: "drinkware",
    subcategorySlug: "tumblers",
    title: "Kids' Sippy Cup",
    shortDescription: "10oz vacuum sippy cup — daycare, kids' parties, school gifts.",
    description: "Insulated 10oz sippy cup with leak-resistant lid and straw. Engraves cleanly. Perfect for daycare and school giveaways.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving", "uv-print"],
    options: { Color: ["Pink", "Teal", "Yellow", "Navy"] },
    heroPromptKey: "product:kids-sippy-cup",
  },
  {
    slug: "full-color-ceramic-mug-15oz",
    categorySlug: "drinkware",
    subcategorySlug: "mugs",
    title: "Full-Color 15oz Ceramic Mug",
    shortDescription: "15oz white ceramic — sublimated edge-to-edge color.",
    description: "Larger 15oz white ceramic mug, dye-sublimated full color. Holds an entire morning's coffee for office gifting.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["sublimation"],
    options: { Color: ["White", "Two-Tone Black", "Two-Tone Red", "Two-Tone Blue"] },
    heroPromptKey: "product:full-color-ceramic-mug-15oz",
  },
  {
    slug: "color-changing-mug",
    categorySlug: "drinkware",
    subcategorySlug: "mugs",
    title: "Color-Changing Sublimation Mug",
    shortDescription: "11oz mug — image reveals when hot liquid is added.",
    description: "Heat-activated color-changing sublimation mug. Black exterior turns clear-white when hot liquid is added, revealing the printed design.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:color-changing-mug",
  },
  {
    slug: "leatherette-mug-sleeve",
    categorySlug: "drinkware",
    subcategorySlug: "mugs",
    title: "Leatherette Mug Sleeve",
    shortDescription: "Slip-on leatherette sleeve for ceramic mugs — engraved.",
    description: "Cream-engraved leatherette sleeve that slips over a standard 11oz ceramic mug. Replaceable, gift-worthy, and reuses your mug inventory.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Wine/Gold"] },
    heroPromptKey: "product:leatherette-mug-sleeve",
  },
  {
    slug: "neoprene-can-cooler",
    categorySlug: "drinkware",
    subcategorySlug: "tumblers",
    title: "Neoprene Can Cooler (Koozie)",
    shortDescription: "Classic neoprene koozie — bulk-friendly screen print.",
    description: "Standard neoprene can koozie — fits 12oz cans. Screen-print or sublimate for events, weddings, and giveaways.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 6,
    decorationMethods: ["screen-print", "sublimation"],
    options: { Color: ["Black", "Red", "Royal", "Navy", "Pink", "Forest", "Yellow"] },
    heroPromptKey: "product:neoprene-can-cooler",
    badges: ["Event Favorite"],
  },
  {
    slug: "leatherette-can-cooler",
    categorySlug: "drinkware",
    subcategorySlug: "tumblers",
    title: "Leatherette Can Cooler",
    shortDescription: "Premium leatherette koozie — engraved monograms.",
    description: "Upscale leatherette can cooler with cream engraving. Wedding-favor and corporate-gift favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Wine/Gold", "Navy/Silver"] },
    heroPromptKey: "product:leatherette-can-cooler",
  },
  {
    slug: "polar-camel-decanter-set",
    categorySlug: "drinkware",
    subcategorySlug: "wine-sets",
    title: "Polar Camel Decanter Set",
    shortDescription: "Glass decanter + 4 glasses on a wooden tray — engraved.",
    description: "Crystal-clear glass decanter with four matching whiskey glasses on an engraved wooden display tray. Premium executive gift set.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving", "sand-etch"],
    heroPromptKey: "product:polar-camel-decanter-set",
    badges: ["Premium"],
  },
  {
    slug: "wine-tool-gift-set",
    categorySlug: "drinkware",
    subcategorySlug: "wine-sets",
    title: "Wine Tool Gift Set",
    shortDescription: "Corkscrew + foil cutter + pourer + stopper — leatherette case.",
    description: "Four-piece wine tool set — waiter's corkscrew, foil cutter, pourer, and stopper — in a leatherette presentation case. Engrave the case.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:wine-tool-gift-set",
  },
  {
    slug: "shot-glass-set",
    categorySlug: "drinkware",
    subcategorySlug: "wine-sets",
    title: "Engraved Shot Glass Set (4-pack)",
    shortDescription: "Four 1.5oz shot glasses with engraved monogram or logo.",
    description: "Set of four heavy-base 1.5oz shot glasses, sand-etched front-and-center. Bar gifts, groomsmen, or branded merch.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 6,
    decorationMethods: ["sand-etch"],
    heroPromptKey: "product:shot-glass-set",
  },
  {
    slug: "stainless-bottle-opener-keychain",
    categorySlug: "drinkware",
    subcategorySlug: "bottle-openers",
    title: "Bottle Opener Keychain",
    shortDescription: "Pocket bottle opener on split ring — engraved.",
    description: "Stainless bottle opener integrated into a keychain. Engraves cleanly. Bulk-friendly for events and weddings.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 6,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:bottle-opener-keychain",
  },
  {
    slug: "wood-bottle-opener-wall",
    categorySlug: "drinkware",
    subcategorySlug: "bottle-openers",
    title: "Wall-Mount Wooden Bottle Opener",
    shortDescription: "Walnut wall-mount opener with cap-catcher.",
    description: "Walnut wall-mount bottle opener with magnetic cap-catcher. Engraved family name or bar-room sign — man-cave staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:wood-wall-bottle-opener",
  },
  {
    slug: "cork-coaster-set",
    categorySlug: "drinkware",
    subcategorySlug: "coasters",
    title: "Cork Coaster Set",
    shortDescription: "6-pack natural cork coasters — laser-burned design.",
    description: "Six round natural cork coasters in a holder. Laser engraving burns crisp lines. Earthy gift option.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:cork-coaster-set",
  },
  {
    slug: "bamboo-coaster-set",
    categorySlug: "drinkware",
    subcategorySlug: "coasters",
    title: "Bamboo Coaster Set",
    shortDescription: "4-pack bamboo coasters — natural earth-tone gift.",
    description: "Four bamboo coasters with cork backing in a matching tray. Engraves a warm dark mark.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:bamboo-coaster-set",
  },
  {
    slug: "silicone-grip-coaster",
    categorySlug: "drinkware",
    subcategorySlug: "coasters",
    title: "Silicone-Grip Coaster",
    shortDescription: "Slip-resistant silicone coaster with engraving area.",
    description: "Slip-resistant silicone coaster with raised lip. Available in solid colors with laser-friendly center panel.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 6,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Navy", "Red", "Forest"] },
    heroPromptKey: "product:silicone-grip-coaster",
  },
  {
    slug: "powder-coated-flask",
    categorySlug: "drinkware",
    subcategorySlug: "flasks",
    title: "Powder-Coated 6oz Flask",
    shortDescription: "Stainless 6oz flask with powder-coat finish — laser engrave.",
    description: "Standard 6oz stainless flask with matte powder-coat finish. Engraves to a clean silver mark.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 6,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "White", "Navy", "Burgundy", "Sage"] },
    heroPromptKey: "product:powder-coated-flask",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // SPORT-SPECIFIC RESIN TROPHIES — fill out the 14 sports
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "resin-bowling-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Bowling Trophy",
    shortDescription: "Hand-painted bowling figure — league night staple.",
    description: "Resin bowler figure on a weighted black base with engraved plate. League finale and tournament favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ['6"', '8"', '10"', '12"'] },
    heroPromptKey: "product:resin-bowling",
  },
  {
    slug: "resin-golf-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Golf Trophy",
    shortDescription: "Golfer mid-swing figure — country-club tournaments.",
    description: "Hand-painted resin golfer mid-swing on a weighted base. Engraving plate for player, tournament, and date.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ['6"', '8"', '10"', '12"'] },
    heroPromptKey: "product:resin-golf",
  },
  {
    slug: "resin-hockey-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Hockey Trophy",
    shortDescription: "Hockey player mid-stride — youth-league tournament.",
    description: "Resin hockey player figure on a weighted base. Plate engraves player, position, and season.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ['6"', '8"', '10"', '12"'] },
    heroPromptKey: "product:resin-hockey",
  },
  {
    slug: "resin-martial-arts-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Martial Arts / Wrestling Trophy",
    shortDescription: "Martial-arts figure — dojo tournament awards.",
    description: "Resin martial-arts figure on a weighted black base. Available in multiple poses and sizes for graded tournament tiers.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ['6"', '8"', '10"', '12"'] },
    heroPromptKey: "product:resin-martial-arts",
  },
  {
    slug: "resin-pickleball-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Pickleball / Tennis Trophy",
    shortDescription: "Racket-sport figure — pickleball league or tennis club.",
    description: "Resin pickleball or tennis figure on a weighted base with engraving plate. Trending at clubs and rec centers.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ['6"', '8"', '10"', '12"'] },
    heroPromptKey: "product:resin-pickleball",
    badges: ["Trending"],
  },
  {
    slug: "resin-racing-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Racing / Motorsports Trophy",
    shortDescription: "Race-car figure on checker base — track day award.",
    description: "Hand-painted resin race-car figure on a checker-flag base. Karting, sprint, and stock-car tournament awards.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ['6"', '8"', '10"', '12"'] },
    heroPromptKey: "product:resin-racing",
  },
  {
    slug: "resin-swimming-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Swimming Trophy",
    shortDescription: "Swimmer mid-stroke — pool meet award.",
    description: "Resin swimmer figure on a weighted base. Plate engraves swimmer, event, and time. Summer-meet favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ['6"', '8"', '10"', '12"'] },
    heroPromptKey: "product:resin-swimming",
  },
  {
    slug: "resin-track-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Track & Field Trophy",
    shortDescription: "Runner mid-stride — meet finalist trophy.",
    description: "Resin track athlete on a weighted base. Engraves event, place, and meet name.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ['6"', '8"', '10"', '12"'] },
    heroPromptKey: "product:resin-track",
  },
  {
    slug: "resin-volleyball-trophy",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "resin-trophies",
    title: "Resin Volleyball Trophy",
    shortDescription: "Volleyball player mid-spike — club tournament.",
    description: "Resin volleyball player figure mid-spike on a weighted base. Standard club and high-school tournament award.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Size: ['6"', '8"', '10"', '12"'] },
    heroPromptKey: "product:resin-volleyball",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // SPORT-SPECIFIC MEDALS
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "baseball-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "medals",
    title: "Baseball Medal",
    shortDescription: "2-inch baseball insert medal with team-color ribbon.",
    description: "Die-cast 2-inch medal with baseball insert. Includes school-color or team ribbon. Tier-priced bulk.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:baseball-medal",
  },
  {
    slug: "basketball-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "medals",
    title: "Basketball Medal",
    shortDescription: "2-inch basketball insert medal with ribbon.",
    description: "Die-cast 2-inch medal with basketball insert. Bulk pricing tier-discounted from 25 units.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:basketball-medal",
  },
  {
    slug: "football-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "medals",
    title: "Football Medal",
    shortDescription: "2-inch football insert medal with ribbon.",
    description: "Standard 2-inch die-cast football medal with neck ribbon. Pop-Warner and youth-league favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:football-medal",
  },
  {
    slug: "cheer-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "medals",
    title: "Cheer / Gymnastics Medal",
    shortDescription: "2-inch cheer insert medal — competition season.",
    description: "Die-cast 2-inch medal with cheer or gymnastics insert. Includes ribbon. Competition-season classic.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:cheer-medal",
  },
  {
    slug: "soccer-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "medals",
    title: "Soccer Medal",
    shortDescription: "2-inch soccer insert medal — youth-league bulk.",
    description: "Standard die-cast soccer medal, 2-inch, with team-color ribbon. Bulk-priced for season-end.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:soccer-medal",
  },
  {
    slug: "swim-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "medals",
    title: "Swimming Medal",
    shortDescription: "2-inch swimming insert medal — pool meet award.",
    description: "Die-cast 2-inch medal with swimming insert. Standard summer-meet award. Includes ribbon.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:swim-medal",
  },
  {
    slug: "track-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "medals",
    title: "Track & Field Medal",
    shortDescription: "2-inch track insert medal with ribbon.",
    description: "Die-cast 2-inch track and field medal — runner figure insert. Standard for HS and middle-school meets.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:track-medal",
  },
  {
    slug: "academic-attendance-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "academic-awards",
    title: "Perfect Attendance Medal",
    shortDescription: "Recognition medal for perfect attendance — quarterly.",
    description: "Die-cast academic medal with perfect attendance insert. School-color ribbon. Bulk pricing through 1,000 units.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:academic-attendance-medal",
  },
  {
    slug: "academic-music-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "academic-awards",
    title: "Music / Band Medal",
    shortDescription: "2-inch academic medal with music insert.",
    description: "Die-cast medal with music or band insert. End-of-year recognition for orchestra, band, choir, theater.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:academic-music-medal",
  },
  {
    slug: "academic-stem-medal",
    categorySlug: "sports-academic-awards",
    subcategorySlug: "academic-awards",
    title: "STEM / Science Medal",
    shortDescription: "Academic medal for science, math, computer recognition.",
    description: "Die-cast medal with STEM or lamp-of-knowledge insert. School-color ribbon, bulk-priced.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["digital-insert"],
    heroPromptKey: "product:academic-stem-medal",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PROMO / OFFICE — gapromotional.com staples
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "click-pen-promo",
    categorySlug: "custom-printing",
    subcategorySlug: "address-labels",
    title: "Imprinted Click Pen",
    shortDescription: "Classic plastic click pen — imprint your logo at quantity.",
    description: "Bulk-priced click-action ballpoint pen with single-color imprint on the barrel. Trade-show staple, available in many barrel colors.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 6,
    decorationMethods: ["uv-print"],
    options: { Color: ["Black", "Royal", "Red", "White", "Hunter", "Burgundy"] },
    heroPromptKey: "product:click-pen-promo",
  },
  {
    slug: "metal-twist-pen",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Metal Twist-Action Pen",
    shortDescription: "Brushed metal twist pen — engraved name or company.",
    description: "Premium brushed-metal twist-action pen with laser-engraved barrel. Pairs nicely with a leatherette journal or portfolio.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Silver", "Black", "Gunmetal", "Rose Gold"] },
    heroPromptKey: "product:metal-twist-pen",
  },
  {
    slug: "rollerball-gift-pen",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Rollerball Gift Pen with Case",
    shortDescription: "Premium rollerball pen — engraved gift box.",
    description: "Premium rollerball pen with smooth ink flow, packaged in a hinged engravable gift box. Executive-gift staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:rollerball-pen-set",
  },
  {
    slug: "spiral-notebook",
    categorySlug: "custom-printing",
    subcategorySlug: "note-pads",
    title: "Spiral-Bound Notebook",
    shortDescription: "5×7 or 8×11 spiral notebook — full-color cover.",
    description: "Spiral-bound notebook with full-color custom cover and 70-sheet lined interior. Trade-show, school, conference giveaway.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 7,
    decorationMethods: ["digital-print"],
    options: { Size: ["5×7", "8.5×11"] },
    heroPromptKey: "product:spiral-notebook",
  },
  {
    slug: "sticky-note-pad",
    categorySlug: "custom-printing",
    subcategorySlug: "note-pads",
    title: "Custom Sticky Note Pad",
    shortDescription: "3×3 sticky note pads — imprinted with logo.",
    description: "Custom 3×3 sticky note pads, 50 sheets per pad, full-color logo imprint at the top. Bulk-priced for office gifting.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 6,
    decorationMethods: ["digital-print"],
    options: { Size: ["3×3", "3×4", "4×6"] },
    heroPromptKey: "product:sticky-note-pad",
  },
  {
    slug: "usb-flash-drive",
    categorySlug: "custom-printing",
    subcategorySlug: "address-labels",
    title: "Imprinted USB Flash Drive",
    shortDescription: "Branded USB-C / USB-A flash drives — engraved or printed.",
    description: "USB 3.0 flash drives in multiple capacities. Imprint or engrave your logo. Trade-show / new-hire onboarding staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 12,
    decorationMethods: ["laser-engraving", "uv-print"],
    options: { Capacity: ["8GB", "16GB", "32GB", "64GB"], Connector: ["USB-A", "USB-C", "Both"] },
    heroPromptKey: "product:usb-flash-drive",
  },
  {
    slug: "lanyard-printed",
    categorySlug: "custom-printing",
    subcategorySlug: "address-labels",
    title: "Sublimated Lanyard with Badge Clip",
    shortDescription: "Full-color sublimated lanyard for events and offices.",
    description: "Polyester lanyard with full-color sublimation print, swivel clip, and badge attachment. Standard 5/8\" or 3/4\" widths.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 8,
    decorationMethods: ["sublimation"],
    options: { Width: ["5/8\"", "3/4\"", "1\""] },
    heroPromptKey: "product:lanyard-printed",
  },
  {
    slug: "name-badge-pin",
    categorySlug: "custom-printing",
    subcategorySlug: "address-labels",
    title: "Engraved Name Badge",
    shortDescription: "Plastic or metal name badge — pin or magnet back.",
    description: "Two-layer plastic or brushed-metal name badge, laser-engraved with name and title. Pin or magnet back.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["laser-engraving"],
    options: { Material: ["Plastic", "Brushed Metal"], Backing: ["Pin", "Magnet"] },
    heroPromptKey: "product:name-badge-pin",
  },
  {
    slug: "stress-ball-promo",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Imprinted Stress Ball",
    shortDescription: "Foam stress ball — single-color logo imprint.",
    description: "Classic round foam stress ball with single-color logo imprint. Trade-show staple. Other shapes available (heart, brain, football).",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 8,
    decorationMethods: ["uv-print"],
    options: { Color: ["Red", "Blue", "Green", "Yellow", "Pink"], Shape: ["Round", "Heart", "Brain", "Football"] },
    heroPromptKey: "product:stress-ball",
  },
  {
    slug: "mouse-pad-printed",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Full-Color Mouse Pad",
    shortDescription: "Sublimated mouse pad — single-unit or bulk.",
    description: "Standard 7.5×9 mouse pad with sublimated full-color print. Single-unit personalization or bulk corporate.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:mouse-pad-printed",
  },
  {
    slug: "phone-stand-charger",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Wireless Charging Phone Stand",
    shortDescription: "Wireless charger + phone stand — leatherette base, engraved.",
    description: "Wireless charging phone stand with leatherette base. Engrave the base with company logo. Premium executive desk gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 12,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Navy/Silver"] },
    heroPromptKey: "product:phone-stand-charger",
    badges: ["Premium"],
  },
  {
    slug: "power-bank-engraved",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Engraved Power Bank",
    shortDescription: "10000mAh power bank with leatherette face — engravable.",
    description: "Slim 10000mAh power bank with leatherette face panel. Engrave logo or name. Conference and corporate-gift favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 25,
    leadTimeDays: 12,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black/Silver", "Rustic/Gold"] },
    heroPromptKey: "product:power-bank-engraved",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // APPAREL — broader coverage (women's, youth, scrubs variants, jerseys)
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "womens-fitted-tee",
    categorySlug: "apparel-headwear",
    subcategorySlug: "womens",
    title: "Women's Fitted Crew Tee",
    shortDescription: "Tailored ring-spun women's crew — flattering drape.",
    description: "Tailored ring-spun cotton women's crew tee with side seams. Decorates with screen print, DTF, or embroidery.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["screen-print", "dtf", "embroidery"],
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL"], Color: ["White", "Black", "Heather Grey", "Navy", "Pink", "Coral"] },
    heroPromptKey: "product:womens-fitted-tee",
  },
  {
    slug: "womens-vneck-tee",
    categorySlug: "apparel-headwear",
    subcategorySlug: "womens",
    title: "Women's V-Neck Tee",
    shortDescription: "Soft V-neck — boutique-feel team apparel.",
    description: "Soft tri-blend V-neck tee with a flattering scoop. Pairs well with screen print or DTF on the chest.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["screen-print", "dtf"],
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL"], Color: ["Black", "Heather Grey", "Navy", "Mauve", "Sage"] },
    heroPromptKey: "product:womens-vneck-tee",
  },
  {
    slug: "womens-quarter-zip",
    categorySlug: "apparel-headwear",
    subcategorySlug: "womens",
    title: "Women's Quarter-Zip Pullover",
    shortDescription: "Tailored women's 1/4-zip — corporate-uniform pairing.",
    description: "Performance-fabric women's 1/4-zip with feminine cut. Embroiders crisply at the left chest. Pairs with men's same-line.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["embroidery"],
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL", "3XL"], Color: ["Black", "Navy", "Steel Grey", "Maroon"] },
    heroPromptKey: "product:womens-quarter-zip",
  },
  {
    slug: "youth-cotton-tee",
    categorySlug: "apparel-headwear",
    subcategorySlug: "youth",
    title: "Youth Cotton Tee",
    shortDescription: "100% cotton youth tee — sized 2T to YXL.",
    description: "Soft 100% cotton youth crew tee. School and youth-league bulk staple. Sizes 2T through YXL.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["screen-print", "dtf", "heat-transfer"],
    options: { Size: ["2T", "3T", "4T", "YXS", "YS", "YM", "YL", "YXL"], Color: ["White", "Black", "Royal", "Red", "Navy", "Pink"] },
    heroPromptKey: "product:youth-cotton-tee",
  },
  {
    slug: "youth-hoodie",
    categorySlug: "apparel-headwear",
    subcategorySlug: "youth",
    title: "Youth Pullover Hoodie",
    shortDescription: "50/50 youth hoodie — team-store staple.",
    description: "Mid-weight youth pullover hoodie. Decorates well with screen print or DTF. Sizes YXS through YXL.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 8,
    decorationMethods: ["screen-print", "dtf", "embroidery"],
    options: { Size: ["YXS", "YS", "YM", "YL", "YXL"], Color: ["Black", "Navy", "Sport Grey", "Maroon", "Royal"] },
    heroPromptKey: "product:youth-hoodie",
  },
  {
    slug: "infant-onesie",
    categorySlug: "apparel-headwear",
    subcategorySlug: "youth",
    title: "Infant Bodysuit",
    shortDescription: "100% cotton infant onesie — baby-shower or hospital giveaway.",
    description: "100% cotton lap-shoulder infant bodysuit with snap closure. Sizes NB through 24M. Sublimation, DTF, or screen print.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["dtf", "screen-print"],
    options: { Size: ["NB", "6M", "12M", "18M", "24M"], Color: ["White", "Pink", "Sky", "Mint"] },
    heroPromptKey: "product:infant-onesie",
  },
  {
    slug: "performance-tee",
    categorySlug: "apparel-headwear",
    subcategorySlug: "activewear",
    title: "Performance Moisture-Wicking Tee",
    shortDescription: "100% poly performance tee — sport teams, gym promo.",
    description: "Snag-resistant 100% polyester performance tee. Holds DTF and dye-sub well. Team uniform and gym-promo staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 7,
    decorationMethods: ["dtf", "sublimation", "heat-transfer"],
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL"], Color: ["White", "Black", "Royal", "Red", "Navy", "Hunter"] },
    heroPromptKey: "product:performance-tee",
  },
  {
    slug: "sports-jersey",
    categorySlug: "apparel-headwear",
    subcategorySlug: "activewear",
    title: "Sports Jersey",
    shortDescription: "Sublimated team jersey — full custom front + back.",
    description: "Full-sublimation team jersey, custom front numbers, back name and number, and side panels. Soccer, basketball, baseball cuts.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 14,
    decorationMethods: ["sublimation"],
    options: { Cut: ["Soccer", "Basketball", "Baseball", "Football"] },
    heroPromptKey: "product:sports-jersey",
    badges: ["Team Custom"],
  },
  {
    slug: "athletic-shorts",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bottoms",
    title: "Athletic Shorts",
    shortDescription: "Performance shorts with side pockets — team and gym wear.",
    description: "Polyester athletic shorts with elastic waist and pockets. Decorate side leg or hip with team mark.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 8,
    decorationMethods: ["screen-print", "embroidery", "heat-transfer"],
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL"], Color: ["Black", "Navy", "Royal", "Forest", "Maroon"] },
    heroPromptKey: "product:athletic-shorts",
  },
  {
    slug: "sweatpants-fleece",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bottoms",
    title: "Fleece Sweatpants",
    shortDescription: "Mid-weight fleece sweatpants — team-store staple.",
    description: "50/50 fleece sweatpants with elastic waist and ankle cuffs. Embroidered hip logo or screen-print leg.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["screen-print", "embroidery"],
    options: { Size: ["S", "M", "L", "XL", "2XL", "3XL"], Color: ["Black", "Navy", "Sport Grey", "Maroon"] },
    heroPromptKey: "product:sweatpants-fleece",
  },
  {
    slug: "joggers-performance",
    categorySlug: "apparel-headwear",
    subcategorySlug: "bottoms",
    title: "Performance Joggers",
    shortDescription: "Tapered performance joggers — modern athleisure.",
    description: "Tapered jogger with side pockets and elastic ankle cuffs. Performance fabric, embroiders cleanly.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["embroidery", "heat-transfer"],
    options: { Size: ["S", "M", "L", "XL", "2XL"], Color: ["Black", "Navy", "Heather Grey"] },
    heroPromptKey: "product:joggers-performance",
  },
  {
    slug: "scrub-pants",
    categorySlug: "apparel-headwear",
    subcategorySlug: "scrubs-lab-coats",
    title: "Performance Scrub Pants",
    shortDescription: "Soft scrub pants with cargo pockets — clinic uniform.",
    description: "Performance-fabric scrub pants with drawstring waist and cargo pockets. Pairs with the scrub top for full uniform.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 6,
    leadTimeDays: 9,
    decorationMethods: ["embroidery"],
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL", "3XL"], Color: ["Caribbean Blue", "Navy", "Wine", "Black"] },
    heroPromptKey: "product:scrub-pants",
  },
  {
    slug: "doctors-jacket",
    categorySlug: "apparel-headwear",
    subcategorySlug: "scrubs-lab-coats",
    title: "Short Doctor's Jacket",
    shortDescription: "29\" doctor's consultation jacket — embroidered name + credentials.",
    description: "Short 29\" doctor's consultation jacket with notched lapel and three pockets. Personalized name and credentials at left chest.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["embroidery"],
    options: { Size: ["XS", "S", "M", "L", "XL", "2XL", "3XL"] },
    heroPromptKey: "product:doctors-jacket",
  },
  {
    slug: "knit-gloves",
    categorySlug: "apparel-headwear",
    subcategorySlug: "accessories",
    title: "Knit Touch-Screen Gloves",
    shortDescription: "Touch-screen-compatible knit gloves — winter giveaway.",
    description: "Acrylic knit gloves with touch-screen-compatible fingertips. Embroidered or heat-transferred logo on the cuff.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 24,
    leadTimeDays: 9,
    decorationMethods: ["embroidery", "heat-transfer"],
    options: { Color: ["Black", "Charcoal", "Navy", "Burgundy"] },
    heroPromptKey: "product:knit-gloves",
  },
  {
    slug: "scarf-knit",
    categorySlug: "apparel-headwear",
    subcategorySlug: "accessories",
    title: "Knit Scarf",
    shortDescription: "Acrylic knit scarf — embroidered end-panel logo.",
    description: "Mid-weight acrylic knit scarf with embroidered logo on the end panel. Cool-weather corporate gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 10,
    decorationMethods: ["embroidery"],
    options: { Color: ["Black", "Charcoal", "Burgundy", "Navy", "Forest"] },
    heroPromptKey: "product:scarf-knit",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PERSONALIZED GIFTS — slate, BBQ, knife sets, more leatherette
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "slate-cheese-board",
    categorySlug: "personalized-gifts",
    subcategorySlug: "cutting-boards",
    title: "Slate Cheese Board",
    shortDescription: "Natural-edge slate cheese board — laser engraves white.",
    description: "Natural-edge slate cheese board with cork feet. Laser engraves a clean white mark. Wedding and housewarming favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 6,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["8×12", "12×16", "16×20"] },
    heroPromptKey: "product:slate-cheese-board",
  },
  {
    slug: "wood-charcuterie-board",
    categorySlug: "personalized-gifts",
    subcategorySlug: "cutting-boards",
    title: "Acacia Charcuterie Board",
    shortDescription: "Long acacia charcuterie board — engraved family name or date.",
    description: "Long acacia charcuterie board with engraved family monogram or wedding date. Premium gift presentation.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["18×8", "24×8", "30×10"] },
    heroPromptKey: "product:wood-charcuterie-board",
  },
  {
    slug: "bbq-grill-set",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "BBQ Grill Set",
    shortDescription: "Stainless BBQ tools in leatherette case — engraved.",
    description: "Three-piece stainless BBQ tool set (spatula, tongs, fork) in a leatherette presentation case. Engrave the case lid.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 8,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:bbq-grill-set",
  },
  {
    slug: "pocket-knife-engraved",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Engraved Folding Pocket Knife",
    shortDescription: "Folding pocket knife with wood handle — engraved blade or handle.",
    description: "Premium folding pocket knife with hardwood handle and stainless blade. Engrave the blade or handle. Groomsman / executive gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Handle: ["Walnut", "Rosewood", "Olive"] },
    heroPromptKey: "product:pocket-knife-engraved",
  },
  {
    slug: "leatherette-key-ring",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leatherette Key Ring",
    shortDescription: "Leather-tag key ring — engraved monogram.",
    description: "Slim leatherette tag with split-ring keychain. Engraves cream monogram. Bulk-friendly for events.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 5,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Rustic", "Wine", "Navy"] },
    heroPromptKey: "product:leatherette-key-ring",
  },
  {
    slug: "luggage-tag-leatherette",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leatherette Luggage Tag",
    shortDescription: "Travel-ready luggage tag — name and contact engraved.",
    description: "Sturdy leatherette luggage tag with leather strap. Engrave name and contact info. Travel-club and corporate-gift staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 5,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Rustic", "Wine", "Navy"] },
    heroPromptKey: "product:luggage-tag-leatherette",
  },
  {
    slug: "leatherette-iPad-portfolio",
    categorySlug: "personalized-gifts",
    subcategorySlug: "leatherette",
    title: "Leatherette Tablet Portfolio",
    shortDescription: "Standard tablet-sized portfolio — engraved cover.",
    description: "Tablet-sized portfolio with interior pocket and elastic closure. Engraves cream cream-on-leatherette monogram on the cover.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Rustic", "Navy", "Wine"] },
    heroPromptKey: "product:leatherette-tablet-portfolio",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CORPORATE AWARDS — additional formats
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "glass-tower-award",
    categorySlug: "corporate-awards",
    subcategorySlug: "glass-awards",
    title: "Glass Tower Award",
    shortDescription: "Tinted glass tower with sand-etched front face.",
    description: "Modern tinted-glass tower mounted on a black base. Sand-etched front face holds names, years, accomplishments.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving", "sand-etch"],
    options: { Size: ["8\"", "10\"", "12\""], Tint: ["Clear", "Smoke", "Blue"] },
    heroPromptKey: "product:glass-tower-award",
  },
  {
    slug: "eagle-glass-trophy",
    categorySlug: "corporate-awards",
    subcategorySlug: "glass-awards",
    title: "Eagle Glass Trophy",
    shortDescription: "Sculpted glass eagle on black base — engraved plate.",
    description: "Sculpted clear-glass eagle in flight on a polished black base. Engraved presentation plate. Leadership-award favorite.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 11,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["10\"", "12\""] },
    heroPromptKey: "product:eagle-glass-trophy",
  },
  {
    slug: "marble-paperweight",
    categorySlug: "corporate-awards",
    subcategorySlug: "desk-pieces",
    title: "Marble Paperweight",
    shortDescription: "Engraved marble paperweight — desk-piece classic.",
    description: "Solid marble paperweight engraved with company logo or recognition text. Desk-piece staple in black, green, or burgundy marble.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 9,
    decorationMethods: ["laser-engraving"],
    options: { Color: ["Black", "Green", "Burgundy"] },
    heroPromptKey: "product:marble-paperweight",
  },
  {
    slug: "mantel-clock",
    categorySlug: "corporate-awards",
    subcategorySlug: "clocks",
    title: "Engraved Mantel Clock",
    shortDescription: "Walnut mantel clock with engraved presentation plate.",
    description: "Classic walnut mantel clock with brass face and engraved presentation plate. Premium retirement gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 10,
    decorationMethods: ["laser-engraving"],
    heroPromptKey: "product:mantel-clock",
    badges: ["Retirement Gift"],
  },
  {
    slug: "office-door-sign",
    categorySlug: "corporate-awards",
    subcategorySlug: "office-signage",
    title: "Engraved Office Door Sign",
    shortDescription: "Wall- or door-mount sign — name + title engraved.",
    description: "Engraved acrylic, wood, or metal office sign for door or wall mount. Name and title on multiple lines.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 6,
    decorationMethods: ["laser-engraving"],
    options: { Material: ["Acrylic", "Walnut", "Brushed Metal"], Mount: ["Wall", "Door"] },
    heroPromptKey: "product:office-door-sign",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PHOTO GIFTS — additional variants
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "photo-blanket",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Photo Blanket",
    shortDescription: "50×60 sublimated fleece blanket — full-color photo print.",
    description: "Soft 50×60 fleece throw blanket with full-color sublimated photo or collage. Standard memorial / family-gift item.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 9,
    decorationMethods: ["sublimation"],
    options: { Size: ["50×60", "60×80"] },
    heroPromptKey: "product:photo-blanket",
  },
  {
    slug: "photo-puzzle",
    categorySlug: "photo-gifts",
    subcategorySlug: "novelty",
    title: "Photo Jigsaw Puzzle",
    shortDescription: "Sublimated 100, 252, or 500 piece puzzle — gift-boxed.",
    description: "Custom-photo jigsaw puzzle in three piece-counts. Comes in a gift box. Unique grandparent / kids' gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["sublimation"],
    options: { Pieces: ["100", "252", "500"] },
    heroPromptKey: "product:photo-puzzle",
  },
  {
    slug: "phone-grip-popsocket",
    categorySlug: "photo-gifts",
    subcategorySlug: "phone-accessories",
    title: "Custom Phone Grip",
    shortDescription: "Pop-out phone grip — full-color sublimated cap.",
    description: "Sublimated full-color phone grip with collapsible cap. Bulk swag for conferences and giveaways.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 7,
    decorationMethods: ["sublimation"],
    heroPromptKey: "product:phone-grip-popsocket",
  },
  {
    slug: "pet-urn-engraved",
    categorySlug: "photo-gifts",
    subcategorySlug: "pet-items",
    title: "Engraved Pet Memorial Urn",
    shortDescription: "Wooden pet urn — engraved name, dates, photo plate.",
    description: "Solid wood pet memorial urn with engraved name and dates, plus an optional photo plate. Compassionate gift.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["laser-engraving"],
    options: { Size: ["Small", "Medium", "Large"] },
    heroPromptKey: "product:pet-urn-engraved",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CUSTOM PRINTING — additional formats and event/wedding stationery
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "wedding-invitation-suite",
    categorySlug: "custom-printing",
    subcategorySlug: "holiday-cards",
    title: "Wedding Invitation Suite",
    shortDescription: "Invite + RSVP + envelope set — foil and letterpress options.",
    description: "Standard 5×7 wedding invitation set: main invite, RSVP card, and envelopes. Choose foil, letterpress, or digital.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 14,
    decorationMethods: ["offset-print", "foil"],
    heroPromptKey: "product:wedding-invitation-suite",
    badges: ["Premium"],
  },
  {
    slug: "save-the-date-magnet",
    categorySlug: "custom-printing",
    subcategorySlug: "magnet-calendars",
    title: "Save-the-Date Magnet",
    shortDescription: "5×7 photo save-the-date magnet — wedding favorite.",
    description: "5×7 photo magnet save-the-dates with envelopes. Standard wedding-stationery format.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 7,
    decorationMethods: ["digital-print"],
    heroPromptKey: "product:save-the-date-magnet",
  },
  {
    slug: "thank-you-card",
    categorySlug: "custom-printing",
    subcategorySlug: "holiday-cards",
    title: "Folded Thank-You Card",
    shortDescription: "Folded 4.25×5.5 thank-you cards with envelopes.",
    description: "Folded 4.25×5.5 thank-you cards on 14pt cover with white envelopes. Wedding, baby-shower, or business follow-ups.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 50,
    leadTimeDays: 6,
    decorationMethods: ["digital-print", "foil"],
    heroPromptKey: "product:thank-you-card",
  },
  {
    slug: "rack-card",
    categorySlug: "custom-printing",
    subcategorySlug: "flyers",
    title: "Rack Card",
    shortDescription: "4×9 rack cards — hotel, real-estate, retail.",
    description: "Standard 4×9 rack cards on 14pt cover, full color both sides. Fits hotel and retail card racks.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 250,
    leadTimeDays: 5,
    decorationMethods: ["digital-print", "offset-print"],
    heroPromptKey: "product:rack-card",
  },
  {
    slug: "presentation-folder",
    categorySlug: "custom-printing",
    subcategorySlug: "brochures",
    title: "Presentation Folder",
    shortDescription: "Pocket folder with optional business-card slits.",
    description: "9×12 pocket folder with optional business-card slits and printed insert pockets. Sales-kit and onboarding-pack staple.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 9,
    decorationMethods: ["offset-print"],
    heroPromptKey: "product:presentation-folder",
  },
  {
    slug: "perfect-bound-booklet",
    categorySlug: "custom-printing",
    subcategorySlug: "booklets",
    title: "Perfect-Bound Booklet",
    shortDescription: "Square-spine booklet — annual reports, lookbooks, programs.",
    description: "Perfect-bound booklet with square spine. 8.5×11 or custom sizes, 50–200 pages. Annual reports, lookbooks, event programs.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 12,
    decorationMethods: ["offset-print"],
    heroPromptKey: "product:perfect-bound-booklet",
  },
  {
    slug: "saddle-stitched-booklet",
    categorySlug: "custom-printing",
    subcategorySlug: "booklets",
    title: "Saddle-Stitched Booklet",
    shortDescription: "Stapled-spine booklet — programs, catalogs.",
    description: "Saddle-stitched (stapled-spine) booklet. 8.5×5.5 or 8.5×11, 8–48 pages. Programs, mini-catalogs, magazines.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 100,
    leadTimeDays: 9,
    decorationMethods: ["offset-print"],
    heroPromptKey: "product:saddle-stitched-booklet",
  },
  {
    slug: "fabric-banner",
    categorySlug: "custom-printing",
    subcategorySlug: "banners",
    title: "Fabric Banner",
    shortDescription: "Polyester fabric banner — wrinkle-resistant, indoor.",
    description: "Dye-sublimated polyester fabric banner with hemmed edges. Wrinkle-resistant, drapes well. Better for indoor/event use.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: ["sublimation"],
    options: { Size: ["3×6", "4×8", "Custom"] },
    heroPromptKey: "product:fabric-banner",
  },
  {
    slug: "mesh-banner",
    categorySlug: "custom-printing",
    subcategorySlug: "banners",
    title: "Wind-Through Mesh Banner",
    shortDescription: "Mesh vinyl banner — passes wind on fences and large outdoor.",
    description: "Mesh vinyl banner that allows wind to pass through. Standard for fence wraps and large outdoor billboards.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["digital-print"],
    options: { Size: ["4×8", "6×10", "Custom"] },
    heroPromptKey: "product:mesh-banner",
  },
  {
    slug: "metal-yard-sign",
    categorySlug: "custom-printing",
    subcategorySlug: "yard-signs",
    title: "Metal Yard Sign",
    shortDescription: "Aluminum yard sign — rigid alternative to coroplast.",
    description: "Premium 0.04\" aluminum yard sign with full-color print. Rigid and weather-resistant alternative to corrugated plastic.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["digital-print"],
    options: { Size: ["18×24", "24×36"] },
    heroPromptKey: "product:metal-yard-sign",
  },
  {
    slug: "custom-window-decal",
    categorySlug: "custom-printing",
    subcategorySlug: "window-decals",
    title: "Window Decal (Cut or Printed)",
    shortDescription: "Cut-vinyl or full-color printed window decals.",
    description: "Window decals in cut vinyl (single color, no background) or full-color printed clear vinyl. Spec your size and quantity.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: ["digital-print"],
    options: { Type: ["Cut Vinyl", "Full-Color Printed", "Frosted Etched"] },
    heroPromptKey: "product:custom-window-decal",
  },

  // ═══════════════════════════════════════════════════════════════════════
  // BULK BLANKS — more wholesale staples
  // ═══════════════════════════════════════════════════════════════════════
  {
    slug: "blank-sublimation-shirts-case",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-apparel",
    title: "Blank Sublimation-Ready Tees — Case (72 ct)",
    shortDescription: "72 polyester sublimation-ready tees — case-priced.",
    description: "Case of 72 polyester sublimation-ready tees, mix sizes. Optimized for in-house dye-sublimation production.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: [],
    options: { Color: ["White", "Sport Grey", "Light Blue"] },
    heroPromptKey: "product:blank-sublimation-shirts-case",
  },
  {
    slug: "blank-tote-natural-case",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-bags-totes",
    title: "Blank Natural Canvas Totes — Case (60 ct)",
    shortDescription: "60 natural-canvas totes — case-priced for resale or print.",
    description: "Case of 60 heavy 12oz natural-canvas totes. Case discount vs. dozen pricing. Stage for printing or resell as-is.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: [],
    heroPromptKey: "product:blank-totes-natural-case",
  },
  {
    slug: "blank-water-bottles-case",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-drinkware",
    title: "Blank Stainless Water Bottles — Case (24 ct)",
    shortDescription: "Case of 24 stainless water bottles — engrave or resell.",
    description: "Case of 24 vacuum-insulated stainless water bottles, 20oz, single colorway per case. For in-house engraving or wholesale resale.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 4,
    decorationMethods: [],
    options: { Color: ["Stainless", "Black", "Navy", "Sage"] },
    heroPromptKey: "product:blank-water-bottles-case",
  },
  {
    slug: "blank-mug-sleeves",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-vinyl-transfers",
    title: "Blank Leatherette Mug Sleeves",
    shortDescription: "Leatherette mug sleeves — engrave-ready, ship to your shop.",
    description: "Engrave-ready leatherette mug sleeves in multiple colors. Sized to fit standard 11oz ceramic mugs. Bulk-priced.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 12,
    leadTimeDays: 4,
    decorationMethods: [],
    options: { Color: ["Black/Silver", "Rustic/Gold", "Wine/Gold", "Navy/Silver"] },
    heroPromptKey: "product:blank-mug-sleeves",
  },
  {
    slug: "blank-pens-bulk",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-paper-stock",
    title: "Blank Click Pens — Box (250 ct)",
    shortDescription: "Box of 250 blank click pens — engrave or print in-house.",
    description: "Box of 250 blank plastic click pens in a single barrel color. Stage for in-house imprint or resell as-is.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: [],
    options: { Color: ["White", "Black", "Royal", "Red"] },
    heroPromptKey: "product:blank-pens-bulk",
  },
  {
    slug: "blank-medals-bulk",
    categorySlug: "bulk-blanks",
    subcategorySlug: "blank-awards-plaques",
    title: "Blank Medal Blanks — Box (100 ct)",
    shortDescription: "Box of 100 blank die-cast medals — engrave-ready.",
    description: "Box of 100 blank 2-inch die-cast medals in gold/silver/bronze finishes. Engrave-ready or insert holders, ribbons sold separately.",
    basePriceCents: null,
    priceStatus: "quote",
    minQty: 1,
    leadTimeDays: 5,
    decorationMethods: [],
    options: { Finish: ["Gold", "Silver", "Bronze", "Antique", "Mixed"] },
    heroPromptKey: "product:blank-medals-bulk",
  },
];
