"use client";

import {
  FontAwesomeIcon,
  type FontAwesomeIconProps,
} from "@fortawesome/react-fontawesome";
import { config, library } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import {
  faArrowRight,
  faArrowLeft,
  faArrowRotateLeft,
  faArrowRotateRight,
  faBagShopping,
  faBars,
  faBolt,
  faBoxesStacked,
  faBrush,
  faCalendarDays,
  faCheck,
  faChevronRight,
  faCircleCheck,
  faCircleInfo,
  faClock,
  faCloudArrowUp,
  faCoffee,
  faCreditCard,
  faDollarSign,
  faEnvelopeOpenText,
  faFeather,
  faFileArrowUp,
  faFire,
  faFlag,
  faGem,
  faGift,
  faGlobe,
  faHammer,
  faHeart,
  faHome,
  faImage,
  faLayerGroup,
  faLightbulb,
  faLocationDot,
  faMagicWandSparkles,
  faMagnifyingGlass,
  faMapPin,
  faMedal,
  faMugHot,
  faPalette,
  faPaperPlane,
  faPhone,
  faPrint,
  faScissors,
  faShieldHalved,
  faShirt,
  faShop,
  faSignsPost,
  faSitemap,
  faSquare,
  faStar,
  faTag,
  faThumbsUp,
  faTrashCan,
  faTrophy,
  faTruckFast,
  faUser,
  faUsers,
  faWandSparkles,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

config.autoAddCss = false;

library.add(
  faArrowRight,
  faArrowLeft,
  faArrowRotateLeft,
  faArrowRotateRight,
  faBagShopping,
  faBars,
  faBolt,
  faBoxesStacked,
  faBrush,
  faCalendarDays,
  faCheck,
  faChevronRight,
  faCircleCheck,
  faCircleInfo,
  faClock,
  faCloudArrowUp,
  faCoffee,
  faCreditCard,
  faDollarSign,
  faEnvelopeOpenText,
  faFeather,
  faFileArrowUp,
  faFire,
  faFlag,
  faGem,
  faGift,
  faGlobe,
  faHammer,
  faHeart,
  faHome,
  faImage,
  faLayerGroup,
  faLightbulb,
  faLocationDot,
  faMagicWandSparkles,
  faMagnifyingGlass,
  faMapPin,
  faMedal,
  faMugHot,
  faPalette,
  faPaperPlane,
  faPhone,
  faPrint,
  faScissors,
  faShieldHalved,
  faShirt,
  faShop,
  faSignsPost,
  faSitemap,
  faSquare,
  faStar,
  faTag,
  faThumbsUp,
  faTrashCan,
  faTrophy,
  faTruckFast,
  faUser,
  faUsers,
  faWandSparkles,
  faXmark,
);

export type IconName = FontAwesomeIconProps["icon"];

export function Icon(props: FontAwesomeIconProps) {
  return <FontAwesomeIcon {...props} />;
}
