/**
 * Pull the 154 orphan DB products (slugs not in the static catalog) and emit
 * a TypeScript module that exposes them as a `SampleProduct[]` array.
 *
 * Output: lib/catalog/recovered-orphan-blanks.ts
 *
 * After this runs, sample-products.ts imports + spreads the array so the
 * orphans appear on the public site in their proper subcategory.
 *
 * Idempotent — re-running regenerates the file from the current DB state.
 */
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
import { createClient } from "@supabase/supabase-js";
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { sampleProducts } from "../lib/catalog/sample-products";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, "../lib/catalog/recovered-orphan-blanks.ts");

type DbProduct = {
  slug: string;
  title: string;
  brand: string | null;
  short_description: string | null;
  description: string | null;
  base_price_cents: number | null;
  min_qty: number;
  lead_time_days: number;
  price_status: string;
  category_id: string | null;
  subcategory_id: string | null;
  seo_meta: Record<string, unknown> | null;
};

type DbCategory = { id: string; slug: string; name: string; parent_id: string | null };

// Escape a string for use inside a TypeScript double-quoted literal.
function tsString(s: string | null | undefined): string {
  if (s == null) return '""';
  return JSON.stringify(s);
}

async function main() {
  const supa = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SECRET_KEY!,
    { auth: { persistSession: false }, db: { schema: "gaph" } },
  );

  // Static slug index — anything NOT in it is an orphan.
  const staticSlugs = new Set(sampleProducts.map((p) => p.slug));

  // Categories for slug lookup
  const { data: catsData } = await supa
    .from("categories")
    .select("id, slug, name, parent_id");
  const cats = (catsData ?? []) as DbCategory[];
  const catById = new Map(cats.map((c) => [c.id, c]));

  // All DB products (paginated)
  const allRows: DbProduct[] = [];
  for (let from = 0; from < 50_000; from += 1000) {
    const { data, error } = await supa
      .from("products")
      .select("slug, title, brand, short_description, description, base_price_cents, min_qty, lead_time_days, price_status, category_id, subcategory_id, seo_meta")
      .range(from, from + 999);
    if (error) { console.error(error); process.exit(1); }
    if (!data || data.length === 0) break;
    allRows.push(...(data as DbProduct[]));
    if (data.length < 1000) break;
  }

  const orphans = allRows.filter((r) => !staticSlugs.has(r.slug));
  // Stable order by slug for diff-friendly output.
  orphans.sort((a, b) => a.slug.localeCompare(b.slug));

  console.log(`Found ${orphans.length} orphans. Generating TS module…`);

  const lines: string[] = [];
  lines.push(`/**`);
  lines.push(` * lib/catalog/recovered-orphan-blanks.ts`);
  lines.push(` *`);
  lines.push(` * Auto-generated by scripts/generate-recovered-blanks.ts — do not edit by hand.`);
  lines.push(` *`);
  lines.push(` * Supplier-blank products that exist in the Supabase \`products\` table but`);
  lines.push(` * were never added to \`imported-blanks.ts\`. Surfacing them here makes them`);
  lines.push(` * visible on the public site (under their respective apparel subcategories)`);
  lines.push(` * and editable from the admin product list.`);
  lines.push(` */`);
  lines.push(`import type { SampleProduct } from "./sample-products";`);
  lines.push(``);
  lines.push(`export const recoveredOrphanBlanks: SampleProduct[] = [`);

  let skipped = 0;
  for (const o of orphans) {
    // Resolve subcategory slug from DB → static slug (strip `${cat}--` prefix).
    const cat = o.category_id ? catById.get(o.category_id) : null;
    const sub = o.subcategory_id ? catById.get(o.subcategory_id) : null;
    if (!cat || !sub) {
      skipped++;
      continue;
    }
    const catSlug = cat.slug;
    // DB sub slug like "apparel-headwear--caps" → static "caps"
    const subSlug = sub.slug.startsWith(`${catSlug}--`)
      ? sub.slug.slice(catSlug.length + 2)
      : sub.slug;

    const meta = o.seo_meta ?? {};
    const heroPromptKey = (meta.heroPromptKey as string) ?? o.slug;
    const imageSource = (meta.imageSource as string) ?? "supplier-cdn";
    const imageUrl = (meta.imageUrl as string) ?? null;
    const originalImageUrl = (meta.originalImageUrl as string) ?? null;
    const supplierUrl = (meta.supplierUrl as string) ?? null;
    const priceStatus = (o.price_status as "confirmed" | "placeholder" | "quote") ?? "quote";

    lines.push(`  {`);
    lines.push(`    slug: ${tsString(o.slug)},`);
    lines.push(`    categorySlug: ${tsString(catSlug)},`);
    lines.push(`    subcategorySlug: ${tsString(subSlug)},`);
    lines.push(`    title: ${tsString(o.title)},`);
    lines.push(`    shortDescription: ${tsString(o.short_description ?? "")},`);
    lines.push(`    description: ${tsString(o.description ?? "")},`);
    lines.push(`    basePriceCents: ${o.base_price_cents ?? "null"},`);
    lines.push(`    priceStatus: ${tsString(priceStatus)},`);
    lines.push(`    minQty: ${o.min_qty ?? 1},`);
    lines.push(`    leadTimeDays: ${o.lead_time_days ?? 7},`);
    lines.push(`    decorationMethods: [],`);
    if (o.brand) lines.push(`    brand: ${tsString(o.brand)},`);
    lines.push(`    heroPromptKey: ${tsString(heroPromptKey)},`);
    lines.push(`    imageSource: ${tsString(imageSource)} as never,`);
    if (imageUrl) lines.push(`    imageUrl: ${tsString(imageUrl)},`);
    if (originalImageUrl) lines.push(`    originalImageUrl: ${tsString(originalImageUrl)},`);
    if (supplierUrl) lines.push(`    supplierUrl: ${tsString(supplierUrl)},`);
    lines.push(`  } as SampleProduct,`);
  }

  lines.push(`];`);
  lines.push(``);

  writeFileSync(OUT_PATH, lines.join("\n"), "utf8");
  console.log(`✓ Wrote ${OUT_PATH}`);
  console.log(`  Entries: ${orphans.length - skipped}`);
  if (skipped > 0) console.log(`  Skipped (missing category): ${skipped}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
