/**
 * scripts/import-scraped-blanks.ts
 *
 * Reads tmp/scraped-blanks-*.json files produced by scripts/scrape-premier.ts
 * and emits lib/catalog/imported-blanks.ts — a single file exporting a
 * `importedBlanks: SampleProduct[]` array. sample-products.ts re-exports
 * this array concatenated with the existing seedProducts.
 *
 * Each imported product is "quote-only" (no price, no add-to-cart) and uses
 * the supplier's hot-linked Cloudinary image URL via the new imageUrl /
 * imageSource / originalImageUrl / supplierUrl fields.
 *
 * Usage:
 *   npx tsx scripts/import-scraped-blanks.ts          # imports every tmp/scraped-blanks-*.json
 *   npx tsx scripts/import-scraped-blanks.ts --dry    # prints what would be written, no file changes
 */
import fs from "node:fs/promises";
import path from "node:path";

type ScrapedProduct = {
  slug: string;
  title: string;
  supplierPartNumber: string;
  imageUrl: string;
  supplierUrl: string;
  targetCategory: string;
  targetSubcategory: string;
  rawCategoryDesc: string;
  sourceSite: string;
};

const TMP = path.join(process.cwd(), "tmp");
const OUT = path.join(process.cwd(), "lib", "catalog", "imported-blanks.ts");

function escapeQuotes(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function buildEntry(p: ScrapedProduct): string {
  // Brief shopper-facing copy. Quote-priced products don't need the rich
  // 4-paragraph description that custom-printing items have.
  const shortDescription = `${p.title} — supplier blank, quote on request. Decorate with print, embroidery, engraving, or sublimation depending on the substrate.`;
  const description =
    `**Supplier blank** — ${p.title} (Part #${p.supplierPartNumber}). Stocked from our wholesale partner network.\n\n` +
    `**Quote-priced** — Pricing for blanks varies by quantity, decoration method, and lead time. Click "Request a quote" and we'll respond within one business day with tier pricing and shipping.\n\n` +
    `**Decoration options** — Add screen print, embroidery, DTF, sublimation, laser engraving, or UV print depending on the substrate. We'll match the right method to your art.\n\n` +
    `**Lead time** — Most decorated blanks ship in 1-7 business days from approval. Larger orders quoted on request.`;

  return `  {
    slug: "${escapeQuotes(p.slug)}",
    categorySlug: "${escapeQuotes(p.targetCategory)}" as const,
    subcategorySlug: "${escapeQuotes(p.targetSubcategory)}",
    title: "${escapeQuotes(p.title)}",
    shortDescription: "${escapeQuotes(shortDescription)}",
    description: ${JSON.stringify(description)},
    basePriceCents: null,
    priceStatus: "quote" as const,
    minQty: 1,
    leadTimeDays: 7,
    decorationMethods: [],
    brand: "Premier",
    heroPromptKey: "${escapeQuotes(p.slug)}",
    imageSource: "supplier-cdn" as const,
    imageUrl: "${escapeQuotes(p.imageUrl)}",
    originalImageUrl: "${escapeQuotes(p.imageUrl)}",
    supplierUrl: "${escapeQuotes(p.supplierUrl)}",
  },`;
}

async function main() {
  const dryRun = process.argv.includes("--dry");
  const files = (await fs.readdir(TMP).catch(() => [])).filter(
    (f) => f.startsWith("scraped-blanks-") && f.endsWith(".json"),
  );
  if (files.length === 0) {
    console.error(`No scraped-blanks-*.json files found in ${TMP}. Run scripts/scrape-premier.ts first.`);
    process.exit(1);
  }
  console.log(`Reading ${files.length} scrape file(s):`);
  const all: ScrapedProduct[] = [];
  for (const f of files) {
    const raw = await fs.readFile(path.join(TMP, f), "utf8");
    const items = JSON.parse(raw) as ScrapedProduct[];
    console.log(`  ${f}: ${items.length} products`);
    all.push(...items);
  }
  // De-duplicate by slug.
  const seen = new Set<string>();
  const unique = all.filter((p) => {
    if (seen.has(p.slug)) return false;
    seen.add(p.slug);
    return true;
  });
  console.log(`Total unique: ${unique.length}`);

  const fileBody = `/**
 * lib/catalog/imported-blanks.ts
 *
 * Auto-generated by scripts/import-scraped-blanks.ts — do not edit by hand.
 * Re-run the importer to regenerate.
 *
 * These are quote-only blank products (no Add to Cart, no price). Images are
 * hot-linked from supplier CDN via imageUrl. Manager image overrides will
 * persist in Supabase via seo_meta (Phase 1) → dedicated columns (Phase 4).
 */
import type { SampleProduct } from "./sample-products";

export const importedBlanks: SampleProduct[] = [
${unique.map(buildEntry).join("\n")}
];
`;

  if (dryRun) {
    console.log("--- dry run — would write ---");
    console.log(fileBody.slice(0, 800) + "\n...");
    return;
  }
  await fs.writeFile(OUT, fileBody);
  console.log(`✓ wrote ${unique.length} entries → ${OUT}`);
  console.log("Next: ensure sample-products.ts imports `importedBlanks` and concatenates it into sampleProducts, then run npm run db:seed");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
